### ISSUE TITLE
loading EntityFramework.MicrosoftSqlServer in Z.EntityFramework.Plus.EFCore?

### ISSUE THREAD

**Issue by vincentshow** [zzzprojects/EntityFramework-Plus#25] opened 2016-08-12 03:17 UTC
1. installed ef+ by nuget in vs2015. use batchupdate
2.  compiled ok, but exception was thrown with nothing message when running app
3. debug in code, and i found the source was GetInnerValues. 
4. decompile Z.EntityFramework.Plus.EFCore.dll by ilspy, and get code follow

try
	{
		assembly = Assembly.Load(new AssemblyName("EntityFramework.MicrosoftSqlServer, Version = 7.0.0.0, Culture = neutral, PublicKeyToken = adb9793829ddae60"));
	}
	catch (Exception)
	{
		throw new Exception("");
	}

and it will be more convenient if messages(not string.empty) can be shown while exception is thrown, thank you a lot

**Comment by vincentshow** [comment] 2016-08-12 03:40
the framwworks node  in project.json

(my library using ef+)
"frameworks": {
    "netstandard1.6": {
      "imports": [
        "dnxcore50",
        "portable-net452+win81"
      ]
    }
  }

(app that reference above library)
"frameworks": {
   "netcoreapp1.0": {
    "imports": [
      "dotnet5.6",
      "dnxcore50",
      "portable-net45+win8"
    ]
    }
  }

**Comment by zzzprojects** [comment] 2016-08-12 13:58
Wow, thank you for reporting us about the empty exception. We will for sure fix it ASAP this weekend.

We will also fix the issue about library trying to load the assembly by the old name (EntityFramework.MicrosoftSqlServer) instead of the new name (Microsoft.EntityFrameworkCore.SqlServer) for NETSTANDARD

**Comment by zzzprojects** [comment] 2016-08-13 17:50
Hello,

The issue should now be fixed in v1.3.7

The exception will now report a custom error (explaining only SQL Server is currently supported under .NET Core) and the code now try to load the right assembly.

Additionally, we added some net under .NET Standard 1.3 to make sure this issue never happen again.

Let me know if the issue is also fixed from your side.

**Comment by vincentshow** [comment] 2016-08-16 01:05
it's ok after updating to 1.3.8, greatly appreciate

**Comment by zzzprojects** [comment] 2016-08-16 02:46
Closing: User confirmed the fix

**Closed by zzzprojects** 2016-08-16 02:46 UTC
