### ISSUE TITLE
Second query isn't cached

### ISSUE THREAD

**Issue by kalatchev** [zzzprojects/EntityFramework-Plus#146] opened 2017-04-01 00:19 UTC
I've just started using Query Cache. I encountered strange behavior when querying database – **second query actually doesn’t use cache**, but makes roundtrip to database (I've traced it with Profiler). Third and so on queries work as expected. Here is the code:
```vb.net
'First query, touches the databse as expected
Dim d As List(Of Doctor) = ctx.Doctors.FromCache().ToList
Console.ReadKey()

'-----------
'ISSUE: here I have another query to database, insted of getting data from cache
'-----------  
Dim d2 As List(Of Doctor) = ctx.Doctors.FromCache().ToList
Console.ReadKey()

'Works as expected (retrieves data from cache)
Dim d3 As List(Of Doctor) = ctx.Doctors.FromCache().ToList
Console.ReadKey()
```

Hope someone can explain and elaborate if this is a bug or I do something wrong.

P.S.
I'm using Z.EntityFramework.Plus.QueryCache.EF6 ver. **1.4.17**.

**Comment by JonathanMagnan** [comment] 2017-04-02 15:18
Hello @kalatchev ,

Unfortunately, we are not able to reproduce this issue.

Could you try the following code in a fresh project to make sure not another library interfere with our library?

```csharp
using System;
using System.Data.Entity;
using System.Linq;
using Z.EntityFramework.Plus;

namespace Z.Request.QueryCache2
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            // CLEAR
            using (var ctx = new CurrentContext())
            {
                ctx.Doctors.RemoveRange(ctx.Doctors);

                ctx.SaveChanges();
            }

            // SEED
            using (var ctx = new CurrentContext())
            {
                ctx.Doctors.Add(new Doctor {IntColumn = 1});
                ctx.Doctors.Add(new Doctor {IntColumn = 2});
                ctx.Doctors.Add(new Doctor {IntColumn = 3});

                ctx.SaveChanges();
            }

            // TEST
            using (var ctx = new CurrentContext())
            {
                var list = ctx.Doctors.FromCache().ToList();
                Console.ReadKey();

                var list2 = ctx.Doctors.FromCache().ToList();
                Console.ReadKey();

                var list3 = ctx.Doctors.FromCache().ToList();
                Console.ReadKey();
            }
        }

        public class CurrentContext : DbContext
        {
            public CurrentContext() : base("CodeFirstEntities")
            {
            }

            public DbSet<Doctor> Doctors { get; set; }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                modelBuilder.Types().Configure(x => x.ToTable(GetType().DeclaringType != null ? GetType().DeclaringType.FullName.Replace(".", "_") + "_" + x.ClrType.Name : ""));

                base.OnModelCreating(modelBuilder);
            }
        }

        public class Doctor
        {
            public virtual int ID { get; set; }
            public virtual int IntColumn { get; set; }
        }
    }
}
```

**Comment by kalatchev** [comment] 2017-04-02 19:48
Hi Jonathan,

Thanks for reply.

I ran your example and it worked as expected. Gradually I start to migrate it step by step to my case. Finally, I found the difference which breaks it. Very strange, but **it’s in authentication method**. When you use SQL Server with integrated security, it works right. But **when you switch to username and password, queries are first repeated** as I mention in my initial post. Here are the screenshots:

![image](https://cloud.githubusercontent.com/assets/10154711/24590259/d2da1dc4-17f2-11e7-8833-c2536c4c50ca.png)

![image](https://cloud.githubusercontent.com/assets/10154711/24590264/df5ebe42-17f2-11e7-8316-6f6108029f03.png)

Please, test it in your enviroinment and tell me if you are able to reproduce my results.

Best regards,
Mikhail.

**Comment by kalatchev** [comment] 2017-04-02 20:11
... and one more detail - **when I include `Persist Security Info=true` in my connection string, problem disappears**. I took a look at the code and at first glance IMHO problem is in the way you generate keys for cache, specifically in `public static string GetConnectionStringForCacheKey(IQueryable query)` (QueryCacheManager.cs). I'm not sure what exactly the problem is (did not debug it), just an intuition.

**Comment by JonathanMagnan** [comment] 2017-04-03 01:45
Thank you @kalatchev,

We can now successfully reproduce the issue.

Your intuition is good.

We append the connection string to the cache key to make it unique.

- On the first query, the password is part of the connection string
- On the second query, the password is NOT part of the connection string, so it's a different key and query the database again.

When specifying `Persist Security Info=true`, the password is now always part of the connection string.

We added this issue in our weekly sprint.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-04-05 19:57
Hello @kalatchev ,

The v1.4.38 has been released.

Let us know if we successfully fixed the issue in this version.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-04-17 23:25
Hello @kalatchev ,

I will close this issue. Feel free to re-open it if still have the bug

**Closed by JonathanMagnan** 2017-04-17 23:25 UTC
