### ISSUE TITLE
Update with clouser problem.

### ISSUE THREAD

**Issue by huofenghuang** [zzzprojects/EntityFramework-Plus#587] opened 2020-03-05 07:22 UTC
### Description
I have a problem with this code:

return await _context.SysUsers.Where(x => x.Id == userId)
                .UpdateAsync(x => new SysUserEntity { Status = newStatus + x.Status, UpdateTime =  DateTime.Now});

### Exception
MySqlException: Unknown column 's.status' in 'field list'
MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in MySqlDataReader.cs
MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary<string, CachedProcedure> cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in MySqlDataReader.cs
MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList<IMySqlCommand> commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in CommandExecutor.cs
MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in MySqlCommand.cs
MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in MySqlCommand.cs
Z.EntityFramework.Extensions.BatchUpdate.Execute<T>(IQueryable<T> query, Expression<Func<T, T>> updateFactory)
Z.EntityFramework.Plus.BatchUpdateExtensions.Update<T>(IQueryable<T> query, Expression<Func<T, T>> updateFactory, Action<BatchUpdate> batchUpdateBuilder)
Z.EntityFramework.Plus.BatchUpdateExtensions+<>c__DisplayClass2_0<T>.<UpdateAsync>b__0()
System.Threading.Tasks.Task<TResult>.InnerInvoke()
System.Threading.Tasks.Task+<>c.<.cctor>b__274_0(object obj)
System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, object state)
System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, object state)
System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref Task currentTaskSlot, Thread threadPoolThread)
Ecg.AI.Repository.UserRepository.ModifyStatus(string userId, string newStatus) in UserRepository.cs

### Generated SQL
UPDATE `sys_user` AS A
INNER JOIN ( SELECT `s`.`id`, `s`.`create_by`, `s`.`create_time`, `s`.`email`, `s`.`gender`, `s`.`introduction`, `s`.`job_title`, `s`.`mobile`, `s`.`name`, `s`.`organization_id`, `s`.`password`, `s`.`status`, `s`.`update_by`, `s`.`update_time`, `s`.`user_name`, `s`.`user_role`
FROM `sys_user` AS `s`
WHERE `s`.`id` = '1'
           ) AS B ON A.`id` = B.`id`
SET A.`status` = CONCAT('3', `s`.`status`),
A.`update_time` = TIMESTAMP('2020-03-05 14:41:37.093375')

### Further technical details
- Z.EntityFramework.Plus.EFCore:3.0.40
- Database Provider:Pomelo.EntityFrameworkCore.MySql version=“3.1.1”

**Comment by JonathanMagnan** [comment] 2020-03-05 14:09
Hello @huofenghuang ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

Even if you provided already a lot of information, sometimes something is missing and make us loose time such as why on our side we get a different alias then 's' for the `sys_user` table name

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by huofenghuang** [comment] 2020-03-06 06:08
I provide a project sample with this issue
https://github.com/huofenghuang/TestEFPlusUpdate

**Comment by JonathanMagnan** [comment] 2020-03-10 19:38
Hello @huofenghuang ,

The fix has been released in the latest version of `Z.EntityFramework.Extensions`.

You can either update it right now, otherwise, wait on next Monday that we update dependencies

**Closed** 2020-03-24 13:55 UTC
