### ISSUE TITLE
NullReferenceException when using string.Empty in a batch update

### ISSUE THREAD

**Issue by neoGeneva** [zzzprojects/EntityFramework-Plus#411] opened 2018-09-18 00:20 UTC
The following code generates a `NullReferenceException` in `BatchUpdate.ResolveUpdateFromQueryDictValues()`, changing `string.Empty` to `""` fixes it.

```c#
await _db.cart
    .Where(x => x.cookie_guid == sessionId)
    .UpdateAsync(x => new cart()
    {
        email_temp = paymentInfo.EmailTemp ?? x.email_temp ?? string.Empty,
        payment_token_id = newToken.payment_token_id
    });
```

Here's the relevant part of the stack trace:

```
   at Z.EntityFramework.Plus.BatchUpdate.<>c__20`1.<ResolveUpdateFromQueryDictValues>b__20_1(MemberExpression m)
   at Z.EntityFramework.Plus.ExpressionVisitor`1.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at Z.EntityFramework.Plus.ExpressionVisitor`1.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at Z.EntityFramework.Plus.ExpressionVisitor`1.Visit(Expression expression)
   at Z.EntityFramework.Plus.BatchUpdate.ResolveUpdateFromQueryDictValues[T](Expression`1 updateFactory)
   at Z.EntityFramework.Plus.BatchUpdate.GetInnerValues[T](IQueryable`1 query, Expression`1 updateFactory, SchemaEntityType`1 entity)
   at Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
```

And here's a screen grab of the exception:

![image](https://user-images.githubusercontent.com/804724/45657086-f228eb80-bb3c-11e8-9216-a7493ddfae11.png)

Version: Z.EntityFramework.Plus.EF6 1.8.10

**Comment by mdhammad313** [comment] 2023-07-21 22:01
@JonathanMagnan I tried to reproduce this on my end. But its working perfectly.  We can close this issue right ?

**Comment by JonathanMagnan** [comment] 2023-07-24 01:39
Hello @mdhammad313 

Sure, it has been 5 years, so a lot of things has been fixed / improved since this date.

Thank you for letting me know.

Best Regards,

Jon

**Closed by JonathanMagnan** 2023-07-24 01:39 UTC
