### ISSUE TITLE
Batch update/delete question

### ISSUE THREAD

**Issue by icebits** [zzzprojects/EntityFramework-Plus#20] opened 2016-08-08 03:49 UTC
Hi,

I have encountered issues with batch update and delete. It is working fine in v1.2.5, but it throw exception after v1.3.4, including 1.3.5. My project using VS2015, EF 6.1.3 and .net 4.6.1, db first. Can assist to look what is wrong, is it additional code needed after new release? Thanks.

Sample code that trigger issue:

var downloadSource = (from x in ctx.trnDownloadSources
                                                   where x.WindowsLogon.ToUpper() == clientWindowsLogon.WindowsLogonName.ToUpper()
                                                   select x);

                            if (downloadSource.Any())
                            {
                                downloadSource.Update(x => new trnDownloadSource
                                {
                                    IsComplete = 3
                                });
                            }

Oops! A general error has occurred. Please report the issue including the stack trace to our support team: info@zzzprojects.com

at Z.EntityFramework.Plus.Internal.Model.GetConceptualModelString(DbContext this)\r\n   at Z.EntityFramework.Plus.Internal.Model.GetDatabaseFirst(DbContext context)\r\n   at Z.EntityFramework.Plus.InternalExtensions.GetModel(DbContext context)\r\n   at Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)\r\n   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)\r\n   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory)\r\n...

**Comment by zzzprojects** [comment] 2016-08-08 03:56
Thank you icebits for reporting this issue.

It looks to be caused when we try to read the model.

Tomorrow, we will try our code with some model we own to see if we find something missing.

If you can, you can send us directly your model to let us test with it. This will greatly help us to find the issue.

**Database First**
Simply send us your .edmx file.
 
**Code First**
You can generate your XML model by using the following method. 

```csharp
public string GetModelXDocument(DbContext context)
{
    XDocument doc;
    using (var memoryStream = new MemoryStream())
    {
        using (XmlWriter xmlWriter = XmlWriter.Create(memoryStream, new XmlWriterSettings { Indent = true }))
        {
            EdmxWriter.WriteEdmx(context, xmlWriter);
        }
 
        memoryStream.Position = 0;
 
        doc = XDocument.Load(memoryStream);
    }
    return doc.ToString();
}
```

**Comment by icebits** [comment] 2016-08-08 04:16
Hi, where do I send the edmx? By email? Thanks.

**Comment by zzzprojects** [comment] 2016-08-08 04:17
Yes sorry, I forgot to add it.

You can send it here: info@zzzprojects.com

**Comment by zzzprojects** [comment] 2016-08-08 22:52
The .emdx has been received and the answer by email sent.

We discovered the XML was malformatted, and the end tag for "EntityContainerMapping" was missed which cause the issue.

We are waiting for the confirmation if our library is working again by adding the missing tag.

**Comment by icebits** [comment] 2016-08-09 02:49
Hi, must be my mistake over removed the data. I have sent you the untouch edmx for your perusal. Sorry.

**Comment by zzzprojects** [comment] 2016-08-10 00:41
The v1.3.6 has been released.

The issue was caused due to the GetModelName method using the database connection instead of Entity Connection to get the model name.

Let us know if this version is now working

**Comment by icebits** [comment] 2016-08-10 02:51
Hi, the new updates working fine. Thank you for your quick fixed.

**Comment by zzzprojects** [comment] 2016-08-10 03:24
Closing: User confirmed the fix is working

**Closed by zzzprojects** 2016-08-10 03:24 UTC
