### ISSUE TITLE
IncludeOptimized is not working when ProxyCreationEnabled = true

### ISSUE THREAD

**Issue by adamlepkowski** [zzzprojects/EntityFramework-Plus#70] opened 2016-10-31 18:42 UTC
Hi,
I’m trying to use the IncludeOptimized feature with database context where “ProxyCreationEnabled” is enabled  and there is a bug in a source code which makes too many requests to a database.

I have the following query:
` db.Blogs.IncludeOptimized(x => x.Posts)
                    .IncludeOptimized(x => x.Comments)
                    .Where(x => x.BlogId == 1)
                    .ToList();`

In SQL Profiler I can see 3 calls to database:
1)	Blog, Posts, Comments are retrieved in one call as it should work
2)	Posts retrieving
3)	Comments retrieving

With enabled “ProxyCreationEnabled” flag all entities retrieved from a database are created as a dynamic proxy object. There is a source code which tries to get the value of related properties and when it does it then calls go to a database. 

Issue exists in CheckNullRecursive method from QueryIncludeOptimizedNullCollection class in this specific line :
`var value = accessor.GetValue(currentItem); 
`

I tried to solved it but I think it's tricky because you want to initialize empty collection if a value is null and then requests go to a database. I think that there are the following options:
1) stop using QueryIncludeOptimizedNullCollection class. Why did you create it? What was the purpose? Does EF create an empty collection as you do? 
2) find another way to check whether the value exists in a property - I think there is no other option besides your current solution - PropertyInfo.GetValue
3) create second database context for read purpose with disabled ProxyCreationEnabled - it's more like a workaround

Full source code:
```
class Program
    {
        static void Main(string[] args)
        {
            using (var db = new BloggingContext())
            {
                db.Database.Log = Console.Write;
                
                Stopwatch stopwatch = Stopwatch.StartNew();

                db.Blogs.IncludeOptimized(x => x.Posts)
                    .IncludeOptimized(x => x.Comments)
                    .Where(x => x.BlogId == 1)
                    .ToList();

                stopwatch.Stop();
                Console.WriteLine(stopwatch.ElapsedMilliseconds);
            }
        }
    }

    public class BloggingContext : DbContext
    {
        public BloggingContext() : base("name=BloggingContext")
        {
            //this.Configuration.ProxyCreationEnabled = false;
        }

        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Post> Posts { get; set; }
    }

    public class Blog
    {
        public Blog()
        {
            this.Posts = new List<Post>();
            this.Comments = new List<Comment>();
        }

        public int BlogId { get; set; }
        public string Name { get; set; }

        public virtual List<Post> Posts { get; set; }
        public virtual List<Comment> Comments { get; set; }
    }

    public class Post
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }

        public int BlogId { get; set; }
        public virtual Blog Blog { get; set; }
    }

    public class Comment
    {
        public int CommentId { get; set; }
        public string Content { get; set; }
        public int BlogId { get; set; }
        public virtual Blog Blog { get; set; }
    }

```

**Comment by zzzprojects** [comment] 2016-11-01 01:56
Hello @adamlepkowski ,

We successfully reproduced this issue.

The solution we will use will be the same as the issue #57 probably.

We will start to implement this solution this weekend. We are currently a little bit loaded with to-do task from PRO library.

To answer some of your sub-questions:

> stop using QueryIncludeOptimizedNullCollection class. Why did you create it? What was the purpose?
 
Entity Framework Include method create empty collection when no record is found. Include Optimized under the hood uses a projection, but this solution keeps the value to null when no record is found. So to mimic Entity Framework Include, we must do the same.

> Does EF create an empty collection as you do?

Yes, Entity Framework Include does.

> find another way to check whether the value exists in a property - I think there is no other option besides your current solution - PropertyInfo.GetValue

That will be automatically fixed when we will fix the issue. So it doesn't matter.

> create second database context for read purpose with disabled ProxyCreationEnabled - it's more like a workaround

Unfortunately, we cannot. This solution is simple to implement, but some people will report bugs as the entity is not anymore a proxy and some related entities not part of the Include cannot longer load automatically since the entity will not be a proxy.

**Comment by zzzprojects** [comment] 2016-11-07 16:38
Hello @adamlepkowski ,

The v1.4.10 is now available.

Let me know if you still have the issue

Best Regards,

Jonathan

**Comment by adamlepkowski** [comment] 2016-11-11 14:06
Hi, @zzzprojects thank you a lot. It works like a charm :)

**Comment by zzzprojects** [comment] 2016-11-12 22:06
Closing: Fix confirmed

**Closed by zzzprojects** 2016-11-12 22:06 UTC
