### ISSUE TITLE
Incorrect SQL code in update with concatenation

### ISSUE THREAD

**Issue by EF-investigator** [zzzprojects/EntityFramework-Plus#50] opened 2016-09-21 10:41 UTC
I have simple EF entity:
public class Client
{
	public int Id { get; set; }
	[StringLength(50)]
	public string Name { get; set; }
	[StringLength(3)]
	public string CountryCode { get; set; }
}

Trying to update Name field.
ctx.Clients.Where(c => c.CountryCode == "US")
	.Update(c => new Client() { Name = c.Name + " from US" },
		x => { x.Executing = command => commandText = command.CommandText; });

EF throws an exception. Problem is in SQL code in row 4 - it should end with N' from US'

UPDATE A 
SET A.[CountryCode] = @zzz_BatchUpdate_0,
A.[Name] =  
    CASE WHEN (B.[Name] IS NULL) THEN N'' ELSE B.[Name] END + N' 
FROM [dbo].[Clients] AS A
INNER JOIN ( SELECT 
    [Extent1].[Id] AS [Id], 
    [Extent1].[Name] AS [Name], 
    [Extent1].[CountryCode] AS [CountryCode], 
    [Extent1].[Timestamp] AS [Timestamp]
    FROM [dbo].[Clients] AS [Extent1]
    WHERE N'US' = [Extent1].[CountryCode]
           ) AS B ON A.[Id] = B.[Id]

Plugin is Z.EntityFramework.Plus.EF6

**Comment by zzzprojects** [comment] 2016-09-21 15:14
Thank you @EF-investigator ,

We successfully reproduce it.

This issue happens because we use the IndexOf method to try the value before the "FROM" clause.

You can concatenate probably any constant string not containing the word "from". We will try soon to create a permanent fix to allow concatenating any characters.

**Comment by zzzprojects** [comment] 2016-09-25 14:52
Hello @EF-investigator ,

We released the v1.4.4

You should not get anymore an error when concatenating with a string containing the "from" keyword.

Best Regards,

Jonathan

**Comment by zzzprojects** [comment] 2016-10-02 17:45
Closing: Issue Fixed

**Closed by zzzprojects** 2016-10-02 17:45 UTC
