### ISSUE TITLE
Filter disable won't work on the same query

### ISSUE THREAD

**Issue by kf-damianurbaszewski** [zzzprojects/EntityFramework-Plus#155] opened 2017-04-11 09:12 UTC
Hi, I've created filter to my entities:
`this.SoftDeletableFilter = this.Filter<TestEntity>(x => x.Where(a => a.Deleted == false));`

First I call db query with filter enabled, after that I call same query with filter disabled but it returns same results.
`db.Entities.Select(e => e.Name).ToList();`
`db.SoftDeletableFilter.Disable();`
` db.Entities.Select(e => e.Name).ToList();`

EntityFramework somehow caches database query and disabling filter is not invalidating this cache. How can I turn off this EF query caching?
Project repository link: https://github.com/kf-damianurbaszewski/EFQueryCache where you can repeat this case.

Regards
Damian

**Comment by JonathanMagnan** [comment] 2017-04-11 20:27
Hello @kf-damianurbaszewski ,

Thank you for reporting this issue.

It was caused by a fix done this weekend. We made a small mistake by trying to solve another issue.

The v1.4.44 has been released and should now work correctly.

Best Regards,

Jonathan

**Comment by kf-damianurbaszewski** [comment] 2017-04-18 11:45
Hi, after making some changes in my project, I occured the same error. 
Now I use the same context for all actions.
Error always occured when i try call the same action twice (disable or enable) when i call actions 
alternately error also occured after a few calls.
Repo link: https://github.com/kf-damianurbaszewski/EFQueryCache

**Comment by JonathanMagnan** [comment] 2017-04-20 00:36
Hello @kf-damianurbaszewski ,

Thank you,

Using your example, we have easily found & fixed the issue.

It's always the same kind of issue because Interceptor is called only the first time the query is compiled and we try to optimize thing by getting the compiled query for futur call.

I believe we have no other choice than making every query unique when a modification on QueryFilter is made. In short, the query is compiled and will be re-used as long as the filter doesn't change but as soon as a filter modification is made, the query will need to be re-compiled (calling the DbInterceptor).

We will think about it a little bit and release a fix probably this night or tomorrow if it gets accepted.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-04-20 21:12
Hello @kf-damianurbaszewski ,

The v1.4.46 has been released.

Let hope it's the last issue you find in this feature ;)

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-05-17 00:33
Closing: Fix confirmed

**Closed by JonathanMagnan** 2017-05-17 00:33 UTC
