### ISSUE TITLE
Runtime error with future queries in EF Core 2.0 (v1.6.10)

### ISSUE THREAD

**Issue by mtrainham** [zzzprojects/EntityFramework-Plus#213] opened 2017-08-16 21:48 UTC
I'm using the Future LINQ extension method to run separate queries in one trip to the database. Our tests are running against an in memory database, and we are getting the following runtime error in v1.6.10 using EF Core 2.0:

`
System.TypeLoadException : Could not load type 'Microsoft.EntityFrameworkCore.Query.Internal.RelationalQueryContextFactory' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
`

End of stack trace:

`
at Z.EntityFramework.Plus.InternalExtensions.IsInMemoryQueryContext[T](IQueryable'1 query)
 at Z.EntityFramework.Plus.QueryFutureExtensions.Future[T](IQueryable'1 query)
`

The same tests ran fine with EF Core 1.x using version 1.6.7

**Comment by JonathanMagnan** [comment] 2017-08-16 23:51
Hello @mtrainham ,

Our library doesn't support EF Core 2.x, we have started to work on it today,

We will try to support it before next Monday.

Best Regards,

Jonathan

**Comment by shep1987** [comment] 2017-08-17 10:33
If you are just using netstandard2 I have a fork we are using internally that you could build the nuget package for
https://github.com/shep1987/EntityFramework-Plus
This is based off of the PR184

As the PR says this will break net46 hence why I didn't submit a new pr

**Comment by JonathanMagnan** [comment] 2017-08-17 11:42
Thank you @shep1987 ,

I will for sure look at your version as well,

Best Regards,

Jonathan

**Comment by MaklaCof** [comment] 2017-08-17 15:34
I am experiencing same problem in all places where I use Z.EntityFramework.Plus. For example: Future, DeleteAsync ...

**Comment by JonathanMagnan** [comment] 2017-08-18 00:19
Hello @mtrainham , @shep1987 , @MaklaCof 

The v1.6.11 has been released.

I'm not sure if everything works as expected or not since I have a problem to make my unit test project run but all basic test I made worked successfully.

I will close this issue. Feel free to open new issue if you have some problem using the latest version with  EF Core 2.x

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2017-08-18 00:19 UTC

**Comment by MaklaCof** [comment] 2017-08-18 10:52
I can confirm `DeleteAsync()` works. Great job.

**Comment by mtrainham** [comment] 2017-08-18 19:22
Wow that was fast. Thanks for looking into this.

I am no longer getting this error, but I'm now getting a different runtime exception running the same query. I'll open a separate issue for that.
