### ISSUE TITLE
Problem using Contains() with BatchUpdate for MySQL

### ISSUE THREAD

**Issue by jooooel** [zzzprojects/EntityFramework-Plus#126] opened 2017-02-16 09:01 UTC
Hi!
Trying to use `BatchUpdate` but I'm getting the following exception:

```
MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered during command execution. ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Parameter '@gp1' must be defined.
   at MySql.Data.MySqlClient.Statement.SerializeParameter(MySqlParameterCollection parameters, MySqlPacket packet, String parmName, Int32 parameterIndex)
   at MySql.Data.MySqlClient.Statement.InternalBindParameters(String sql, MySqlParameterCollection parameters, MySqlPacket packet)
   at MySql.Data.MySqlClient.Statement.BindParameters()
   at MySql.Data.MySqlClient.Statement.Execute()
   at MySql.Data.MySqlClient.PreparableStatement.Execute()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory)
```

I'm trying to run this update that soft deletes items with a certain language:

```C#
_dataContext
	.AccountItems
	.Include(accountItem => accountItem.Item)
	.Where(accountItem =>
		accountItem.MediaType.SearchProfileId == searchProfile.Id &&
		!accountItem.IsDeleted &&
		removedLanguages.Contains(accountItem.Item.LanguageCode))
	.Update(accountItem => new AccountItem { IsDeleted = true });
```

Without the `Contains()` row, it works fine. 

I'm using
- EntityFramework: 6.1.3
- Z.EntityFramework.Plus.EF6: 1.4.27
- MySql.Data.Entity: 6.9.9
- MySQL: 5.7.16

**Comment by JonathanMagnan** [comment] 2017-02-16 12:19
Hello @jooooel ,

Thank you for reporting.

We will try to fix the issue this weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-02-18 16:08
Hello @jooooel ,

The v1.4.30 has been released.

Let me know if the issue is successfully fixed.

Best Regards,

Jonathan

**Comment by jooooel** [comment] 2017-02-20 13:36
Seems to be working just fine! Thank you :)

**Comment by JonathanMagnan** [comment] 2017-02-20 15:13
Closing Comment: Fix confirmed

**Closed by JonathanMagnan** 2017-02-20 15:13 UTC
