### ISSUE TITLE
Batch delete on query produced with Select statement

### ISSUE THREAD

**Issue by TannerStevenson** [zzzprojects/EntityFramework-Plus#348] opened 2018-04-24 01:26 UTC
Hi,

I am trying to do the following actions:
parentsToRemove = context.Parents.Where(whereExpression)
childrenToRemove = parentsToRemove.Select(p => p.Child)
childrenToRemove.DeleteAsync() <- throws error saying "Invalid column name 'Id'."
parentsToRemove.DeleteAsync()

I was wondering if DeleteAsync is supposed to work with table joins such as this? I have verified that parentsToRemove.DeleteAsync() will run successfully. Also, in this particular situation, cascade-deleting is not possible, which is why i am trying to delete in this fashion.

**Comment by JonathanMagnan** [comment] 2018-04-24 01:35
Hello @TannerStevenson ,

Do you think you could provide us a test project with this issue?

It will make easier/faster for my developer to getting started for investigating it.

_We now always ask for a project since we found out that most issues are missing some essential information or are resolved by the requestor when creating it_

_(Even if the issue seem very easy to reproduce, by getting a test project, it allow us to give a faster support and better experience for the support of all our free libraries)_

Best Regards,

Jonathan

---

**Performance**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by TannerStevenson** [comment] 2018-04-24 01:39
Hi Jonathan,

Does your response mean that your bulk delete methods _should_ work after a Select statement? It might be a little while before I have time to make a sample app to reproduce this.

**Comment by JonathanMagnan** [comment] 2018-04-24 01:43
Hello @TannerStevenson ,

I might be wrong but I have seen some pretty weird scenario with Batch Delete ;)

It might works, this kind of error with `Invalid column name 'Id'." often happen people `Entity Framework` generate the SQL using some alias that we do not support yet.

As said, that will be easier on our side to check it if we have a test project that reproduce this error.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2018-05-15 03:03
Hello @TannerStevenson ,

This issue will be closed since we haven't heard back from you.

Feel free to reopen it if you can provide the information we asked.

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2018-05-15 03:03 UTC
