### ISSUE TITLE
Looks like EF Core 2.0 p1 changes break this library

### ISSUE THREAD

**Issue by ksmithRenweb** [zzzprojects/EntityFramework-Plus#143] opened 2017-03-29 15:48 UTC
I pulled down an EF Core daily build, to test a fix that EF Core accepted this month.
One thing I ran into is that the future library now throws a Null Reference Exception.

My personal guess is that a method signature has changed in EF Core 1.2, and the reflection used in the future library can't find a method now. I don't expect to have time to track this down myself.

The good news is that the performance issue in EF Core when doing left outer joins is resolved in 1.2.
In one extreme case it sped up the call from 600 ms to 200 ms.

**Comment by JonathanMagnan** [comment] 2017-03-29 15:56
Hello @ksmithRenweb ,

I already had some time reserved to look about the new version of EF Core released in March (v1.1.1)

I'm not sure however if we will start to support previous version 1.2.0 (https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.EntityFrameworkCore.SqlServer)

I will for sure try it if I have enough time this weekend.

Best Regards,

Jonathan

**Comment by ksmithRenweb** [comment] 2017-03-29 16:11
Just a note: for efcore 1.1.1 we are not seeing any issues while using UpdateAsync, DeleteAsync or any Future call. But. The sprint with that update has not gone to testers yet either.

**Comment by ksmithRenweb** [comment] 2017-05-17 21:11
I didn't expect it to change since you didn't announce anything. But I retested with the latest preview on nuget. With EF Core 2.0 preview 1 the future library throws an null ref exception.

**Comment by JonathanMagnan** [comment] 2017-05-18 01:10
Hello @ksmithRenweb ,

That's normal. A lot of methods has been modified under the hood by the EF Team.

The good news is we already have a branch that supports EF Core 2.0

At this moment, this is more a decision about how we will support all theses version together.

I mean, we have to support EF5, EF6, EF Core in a different assembly which is easy...

Under EF Core, we need to support in the same assembly 1.0, 1.1, 1.1.1, 2.0... this one start to be though and may lead easily to some issue!

Unfortunately, I already spent this week the time limit I try to allow to this library, so I cannot promise any release during the weekend, but I will keep you updated.

Best Regards,

Jonathan

**Comment by azaytsev-csr** [comment] 2017-07-07 00:46
Any news on this?

**Comment by JonathanMagnan** [comment] 2017-07-07 11:59
Hello @azaytsev-csr ,

We worked on this two weeks ago. If I remember correctly, only one class left that are not compatible with 1.x and 2.x

If we don't find any solution during the weekend, we will release a new version 2.x that will be only compatible with 2.x and up.

So a version should be available for next Monday.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-07-10 18:04
Hello all,

The v1.6.5 has been released. It should now be compatible with 1.x and 2.x

However, it seems we got some problem to run our unit test on the 2.x version, for an unknown reason that appears to be caused by ReSharper, we are not able to run all tests so perhaps we have missed something.

Let me know if the new version is working correctly with 2.x

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-08-18 00:21
Hello @ksmithRenweb ,

A new version is available working with EF Core 2.0 stable.

I will close this issue, feel free to open new issue if you find some problem.

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2017-08-18 00:21 UTC
