### ISSUE TITLE
Skip + Take with IncludeFilter with empty result set locks up

### ISSUE THREAD

**Issue by info-wes** [zzzprojects/EntityFramework-Plus#11] opened 2016-06-03 17:02 UTC
I have a pretty simple setup here with a decent number of records (5,000-6,000) and when I use IncludeFilter with Skip and Take where I'm reaching outside of my result set, instead of returning nothing it just hangs the request.

Example:

[Order] one to many [Items]. Let's say I have 100 orders.

So if I try to take 110 orders like so, my application freezes:

> db.Orders
> .IncludeFilter(o => o.Items.Where(i => i.Cost >= intValue))
> .OrderBy(o => o.Created)
> .Skip(100)
> .Take(10)
> .ToList<Order>();

Yet if I just use a normal Include, like so, it works as expected (returns an empty list)

> db.Orders
> .Include(o => o.Items)
> .OrderBy(o => o.Created)
> .Skip(100)
> .Take(10)
> .ToList<Order>();

**Comment by zzzprojects** [comment] 2016-06-04 13:58
Thank you for reporting this issue,

We can successfully reproduce it. This is happening only with an empty or null collection. A fix should be released this Sunday.

**Comment by zzzprojects** [comment] 2016-06-06 19:13
Unfortunately, we are a little bit late since we wanted to support EFCore R2 as well,

The version will be released Tuesday.

**Comment by zzzprojects** [comment] 2016-06-08 18:51
Hello info-wes,

The version 1.2.0 fixing this issue is now available.

Let us if this version fix your issue or you still have it.

**Comment by zzzprojects** [comment] 2016-07-13 12:47
Closing: Issue fixed

**Closed by zzzprojects** 2016-07-13 12:47 UTC
