### ISSUE TITLE
Configuring Multitenancy with CRUD queries 

### ISSUE THREAD

**Issue by weedkiller** [zzzprojects/EntityFramework-Plus#132] opened 2017-02-24 08:41 UTC
Hi, this is very nice 👍 
For multi-tenant purpose, I have added a `companyId int` field/value to the `aspUsers` table. I also have the `companyId` col in most of the entities/table, and followed your wiki. 

The issue is the default scaffolding in the controllers does not include your Ctx filter at the controller, does setting a global filter automatically over ride or inject into the local controller context? can you tell me how to configure and setup/do this? 

1. So, how can I set a filter during user login, that will user his `tenantId/companyId` to filterOnly his organizations records when the companyId field is available on the entities, and prevent other visibility.
2. Is the filter per session, and does it dispose automatically when user logs out/? how to implement dispose on time-our or user lock-out as well?
3. In wiki help help I only see Query Filter, what about rest CRUD filter like in Dynamic Filters, for updates and deletes on the main table and related tables, can you please include some CRUD filter samples around multitenancy

Thanks
Weedy

**Comment by JonathanMagnan** [comment] 2017-02-27 13:33
Hello @weedkiller ,

Currently, there is an issue in our library for filtering by context.

The query plan is cached globally and not by context which causes some trouble to our library when multiple different filters must exist at the same time (Tenant Filter).

I will give you a better answer to all your questions when this issue will be fixed but meanwhile, I don't recommend using the library for tenant scenario unless the tenant is global (not by the user currently logged)

Best Regards,

Jonathan

**Comment by weedkiller** [comment] 2017-03-02 03:46
ok thanks for letting me know.

In the meantime, can you provide some samples on a different context.

For e.g. filter records by time, last week, last month and grouping etc - does not apply to tenant but on the time domain. The fluentTime lib is nice, but I was hoping to see that aspect in your lib

**Comment by cuongdn** [comment] 2017-03-03 09:40
Hi, I have a same multi tenant bug. The filter always same to every users because of globally query cache, 
@JonathanMagnan Could you tell me how long will it take to fix this bug? I stuck here and deadline is coming closer. Thanks

````
 public EfContext(string nameOrConnectionString)
            : base(nameOrConnectionString)
{
    this.Filter<IHaveTenant>(q => q.Where(x => x.TenantId == UserSessions.TenantId));
}
````

**Comment by JonathanMagnan** [comment] 2017-03-05 04:13
Hello @weedkiller , @cuongdn 

I'm very sorry for the long time I took to try to fix this issue. Unfortunately, free time to support this library is currently very hard to find.

The v1.4.33 has been released
https://github.com/zzzprojects/EntityFramework-Plus/wiki/Downloads

The issue with Tenant filter should now be fixed.

However, there is still some existing limitation.
- LazyLoading is fully compatible with global filter but not with context filter (issue caused by cached query)
- If you use context filter, use SetFiltered method over Set (The Set method have the same problem as LazyLoading)

Let me know if the Query Filter is finally working.

Best Regards,

Jonathan

**Comment by cuongdn** [comment] 2017-03-05 15:55
After upgrade, I get error "Object reference not set to an instance of an object" when using AsNoFilter().SingleOrDefault(...), my app totally broken

Partial stack trace
```
[NullReferenceException: Object reference not set to an instance of an object.]
   Z.EntityFramework.Plus.QueryFilterContextInterceptor.Initialize(DbContext context) +574
   Z.EntityFramework.Plus.QueryFilterContextInterceptor..ctor(DbContext context) +320
   Z.EntityFramework.Plus.QueryFilterManager.AddOrGetFilterContext(DbContext context) +100
   Z.EntityFramework.Plus.QueryFilterInterceptorDbCommandTree.TreeCreated(DbCommandTreeInterceptionContext interceptionContext) +562
   System.Data.Entity.Infrastructure.Interception.DbCommandTreeDispatcher.<Created>b__0(IDbCommandTreeInterceptor i, DbCommandTreeInterceptionContext c) +10
   System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch(TResult result, TInterceptionContext interceptionContext, Action`2 intercept) +148
   System.Data.Entity.Infrastructure.Interception.DbCommandTreeDispatcher.Created(DbCommandTree commandTree, DbInterceptionContext interceptionContext) +160
   System.Data.Entity.Core.Common.DbProviderServices.CreateCommandDefinition(DbCommandTree commandTree, DbInterceptionContext interceptionContext) +99
   System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.CreateCommandDefinition(ObjectContext context, DbQueryCommandTree tree) +142
   System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.Prepare(ObjectContext context, DbQueryCommandTree tree, Type elementType, MergeOption mergeOption, Boolean streaming, Span span, IEnumerable`1 compiledQueryParameters, AliasGenerator aliasGenerator) +159
   System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption) +993
   System.Data.Entity.Core.Objects.<>c__DisplayClass7.<GetResults>b__6() +32
   System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction(Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess) +288
   System.Data.Entity.Core.Objects.<>c__DisplayClass7.<GetResults>b__5() +154
   System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Func`1 operation) +190
   System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption) +283
   System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0() +15
   System.Data.Entity.Internal.LazyEnumerator`1.MoveNext() +45
   System.Linq.Enumerable.SingleOrDefault(IEnumerable`1 source) +121
   System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__2(IEnumerable`1 sequence) +40
   System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle(IEnumerable`1 query, Expression queryRoot) +59
   System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute(Expression expression) +114
   System.Data.Entity.Internal.Linq.DbQueryProvider.Execute(Expression expression) +116
   System.Linq.Queryable.SingleOrDefault(IQueryable`1 source, Expression`1 predicate) +249
```

**Comment by JonathanMagnan** [comment] 2017-03-05 16:35
Hello @cuongdn ,

I will look at this issue today.

Do you think you could provide us an example that's not working to speed-up the bug correction?

All our test-case are currently working.

Best Regards,

Jonathan

**Comment by cuongdn** [comment] 2017-03-06 04:25
Hello,
I fixed this error but I'm not satisfied about this solution. You can see my code as follow repository
https://github.com/cuongdn/efplusfilter

**Problem**
Core.DataAccess (only QueryFilter)
```
 <package id="Z.EntityFramework.Plus.QueryFilter.EF6" version="1.4.33" targetFramework="net452" />
```

DataAccess (all features)
```
  <package id="Z.EntityFramework.Plus.EF6" version="1.4.33" targetFramework="net452" />
```
EfFilter: need nothing
- Using AsNoFilter() => Error: NullReferenceException as previous stack trace

**Solution**
It works when only use ```Z.EntityFramework.Plus.QueryFilter.EF6``` or ```Z.EntityFramework.Plus.EF6``` in both Core + DataAccess (not QueryFilter.EF6 and Plus.EF6)

But project Core.DataAccess actually doesn't need all features, it only need  QueryFilter.EF6. I hope it will help you figure out this bug or explain what I did wrong.

Regards,
Cuong

**Comment by JonathanMagnan** [comment] 2017-03-06 04:32
Thank a lot @cuongdn ,

I will for sure check it tomorrow.

**Comment by cuongdn** [comment] 2017-03-06 07:58
> context.Set only work with GlobalFilter (You can use the method SetFiltered instead)

One more thing, I don't understand what you mean about GlobalFilter because after upgrade using my solution (only upgrade package and no more code), everything still works. I have never used SetFiltered yet and all filtering configurations is in EfContext.

**Comment by JonathanMagnan** [comment] 2017-03-06 13:57
Hello @cuongdn,

Let first explain the difference:

- A global filter is normally creating once when the application start.
- An instance filter is created by context

The Set is still filtered by global and instance filter but once compiled, it caches the query to execute in a shared cache.

### Global Filter
```csharp
// using Z.EntityFramework.Plus; // Don't forget to include this.
QueryFilterManager.Filter<Customer>(q => q.Where(x => x.IsActive));

var ctx = new EntitiesContext();
// TIP: You can also add this line in EntitiesContext constructor instead
QueryFilterManager.InitilizeGlobalFilter(ctx);

// SELECT * FROM Customer WHERE IsActive = true
var list = ctx.Customers.ToList();
```

### Instance Filter
```csharp
// using Z.EntityFramework.Plus; // Don't forget to include this.
var ctx = new EntitiesContext();

ctx .Filter<Customer>(q => q.Where(x => x.IsActive));

// SELECT * FROM Customer WHERE IsActive = true
var list = ctx.Customers.ToList();
```

Here is an example that will not work
```csharp
// Apply some global filter when the application start
QueryFilterManager.Filter<Customer>(q => q.Where(x => x.OrderCount > 5));

var ctx1 = new EntitiesContext();
var ctx2 = new EntitiesContext();

// SELECT * FROM Customer WHERE OrderCount > 5
// The first time the query compile, it's apply and cache the query with all global && instance filter
var list1 = ctx1.Set<Customer>().ToList();

// Apply the filter
ctx2.Filter<Customer>(q => q.Where(x => x.IsActive));

// SELECT * FROM Customer WHERE OrderCount > 5
// Oops! The following set have not been filtered with the instance filter since the cached query has been used
var list1 = ctx2.Set<Customer>().ToList();

// SELECT * FROM Customer WHERE OrderCount > 5 AND IsActive = true
// Now it's work since the SetFiltered has been used
var list1 = ctx2.SetFiltered<Customer>().ToList();

```

**Comment by weedkiller** [comment] 2017-03-06 18:29
Hi @JonathanMagnan , you explained this well between the global and instance filters - now that we understand what you mean by those two, let me clarify. I am seeking is a **hybrid where I can pass in any entity at a per context and per session** but for all entities, if they have a column specified.

for e.g. an **_instance scoped context filter_**  defined with a generic entity/table definition so that, regardless of an interface, `if a table contains a col for tenant` it will filter.  Here `T` is any table/entity `OfTypeGenericEntity` if you look in EF DbSet, you may find it there or you can also discover from [here](http://stackoverflow.com/a/30938268/6085193)
____________
`ctx .Filter<T>(q => q.Where(x => x.user.TenantId));` // tenantMay or _Maynot_ exist in sometables, if its not, then just return all values.
Also make it `fluent`, so we can check, 

         ctx .Filter<T>(q => q.
         .Where(x => x.user.TenantId)
         .Where(rec => rec.IsNotArchived)

 
also a positive note 👍 : what I have found with your framework, is that its more flexible and easier to use than others like dynmfilters etc.

Lastly I know you have libs for sale, and my boss might be interested if we can show performance improvements above regular EF for the CRUD, and not just bulk. If you figure out how to map to Dapper for  reads only, or such, [check out this lib](http://bit.ly/2lwPsMj)

**Comment by JonathanMagnan** [comment] 2017-03-06 20:46
Hello @cuongdn ,

Thank you for your project, now I understand better your issue.

### Problem
The following exception is thrown `Object reference not set to an instance of an object`

### Cause
That error happens if a both library is used within the same solution:

- Assembly A: Z.EntityFramework.Plus.EF6
- Assembly B: Z.EntityFramework.Plus.QueryFilter.EF6

### Solution
Only one of this library can be used in a solution.

Only one assembly will be copied to the output project instead of having two different assemblies.

### Why we will not fix?
While a fix could be possible to allow both libraries within the same solution, some weird behavior will still exist or we will eventually make the same mistake in future changes.

Both libraries contain a set of the filter instead of a library containing all filters. By example calling AsNoFilter() may be handled only by the hook in the Assembly A. But since we remove the workaround used to specify we should not add a filter, the Assembly B hook will not be aware of it and will still apply the filter.

The risk of eventual mistake is a way to high.

I'm not sure if I explained it correctly so let me know if you need more detail, but I highly recommend you to use only the full version since only one library will be used in the final in the output project.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-03-06 20:50
Hello @weedkiller,

Could you contact me directly for the last question about EF CRUD (This thread is enough long hehe)? You may have got a very good idea here if I understand your requirement ;)

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-03-07 02:35
Hello @weedkiller ,

Yes, our library is easier to use but because it not supports only filter but also other methods in the "Filter" method like Take, OrderBy, Include, etc.. We cannot, unfortunately, use the same technique as the DynamicFilter library. So some scenario is currently not supported by our library (Set and Lazy loading for Instance Filter).

So if I understand your requirement for the QueryFilter feature, you want to be able to do something like this?

```csharp
public interface ITenant
{
	public int TenantID { get; set; }
}

public class NotHeritingFromInterface
{
	public int ID { get; set; }
	public int TenantID { get; set; }
}

ctx.Filter<ITenant>(x => x.Where(y => y.TenantID == 2));

// SELECT * FROM NotHeritingFromInterface WHERE TenantID == 2
ctx.NotHeritingFromInterface.ToList();
```

So even if the class NotHeritingFromInterface doesn't inherit from ITenant, the filter is also applied?

Best Regards,

Jonathan

**Comment by weedkiller** [comment] 2017-03-07 03:16
I was saying my EF objects do not implement these interfaces, and I think the `col names` on the table/Entites should be enough to filter.

**Closed** 2021-03-01 17:44 UTC
