### ISSUE TITLE
Future Query got InvalidCastException for System.DateTimeOffset

### ISSUE THREAD

**Issue by baoduy** [zzzprojects/EntityFramework-Plus#458] opened 2019-02-27 01:55 UTC
I'm trying to use the future query for Entity which has CreatedOn and UpdatedOn is DateTimeOffset and got bellow error

`Test threw exception: 
System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.DateTimeOffset'.
`

My Query
```csharp
    var totalItems = query.DeferredCount().FutureValue();
    var items = query.Skip(itemIndex).Take(pageSize).Future();
```

Seems the DeferredCount and FutureValue is not working property with DateTimeOffset

**Comment by JonathanMagnan** [comment] 2019-02-28 02:37
Hello @baoduy ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by baoduy** [comment] 2019-02-28 06:01
Sure let me provide the sample code soon

**Comment by baoduy** [comment] 2019-03-10 07:52
I think the issue happens when I'm using EfCore with SQLite for unit testing. The code works fine with real SQL however die when running my unit tests.

**Comment by JonathanMagnan** [comment] 2019-03-17 14:58
If you success to reproduce it and provide a project, we will be happy to look at it.

Meanwhile, we will close it as we are not able to reproduce it and seem to only appears for `unit test` for an unknown reason ;(

**Closed by JonathanMagnan** 2019-03-17 14:58 UTC
