### ISSUE TITLE
EF6 IncludeFilter issue

### ISSUE THREAD

**Issue by DK-93** [zzzprojects/EntityFramework-Plus#373] opened 2018-06-13 11:30 UTC
Hi,
I'm facing a weird issue with IncludeFilter, however my sample code is almost the same as yours on the 'Documentation' page. I'm using the 'Z.EntityFramework.Plus.EF6' NuGet package with version 1.8.1.

using (TestEntities context = new TestEntities())
{
        var q = context.Users.IncludeFilter(x => x.Equipments.Where(y => y.IsActive)).ToList();
}

And the exception is the following:

System.InvalidCastException: 'Unable to cast object of type '<>f__AnonymousType0`2[User,System.Linq.IQueryable`1[System.Collections.Generic.IEnumerable`1[Equipment]]]' to type 'User'.'

Best Regards,
David

**Comment by JonathanMagnan** [comment] 2018-06-13 12:10
Hello @Jon,

Do you think you could provide a "working" project example/test with this issue?

It will make easier/faster for my developer to getting started for investigating it.

_You can send it to info@zzzprojects.com if you need to keep the source private_

_We now always ask for a project since we found out that most issues are missing some essential information, have some syntax mistake or are resolved by the requestor when creating it_

_(Even if the issue seem very easy to reproduce, by getting a test project, it allow us to give a faster support and better experience for the support of all our free libraries)_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by DK-93** [comment] 2018-06-14 08:05
Hi,

I think I've just figured out what's the problem. My model (edmx) is located in a separate assembly, the model and table objects are hidden via internal visibility. However the service layer can access the model by the 'InternalsVisibleTo' attribute. That's why the exception occurs, when the visibility is public it's just working fine. 

Regards,
David

**Comment by JonathanMagnan** [comment] 2018-06-14 14:00
It there something we can do on our side?

Best Regards,

Jonathan

**Comment by DK-93** [comment] 2018-06-15 08:57
There isn't, the problem is on my side, and I guess the current behavior is the excepted but thank you the support anyway.
Have a nice day!

Regards,
David

**Closed** 2018-06-15 12:29 UTC
