### ISSUE TITLE
InMemory db and bulk updates involving navigation properties 

### ISSUE THREAD

**Issue by MirandaDotNet** [zzzprojects/EntityFramework-Plus#546] opened 2019-11-12 16:01 UTC
### Description
While using unit tests and EF+, we discovered that Batch update doesnt work correctly with navigation props. 
For testing purposes we create in memory database with the following structure:
```
class CUSTOMER{ 
   string ID;
   string ADDRESS_ID;  
   ADDRESS ADDRESS}. 

class ADDRESS{ 
   string ADDRESS_ID;}. 
```
ADDRESS_ID is mapped to ADDRESS and is a foreign key to another table of ADDRESS  it is filled automatically by EF.

In our code we bulk update ADDRESS_ID with some other value.

###Example from unit tests:
```
// set up context with dummy data
...
Context.SaveChanges();

//bulk update
//this code doesnt work
Context.CUSTOMERS.Update(x => new CUSTOMER() {ADDRESS_ID = "some other address value"});
```

all BUT ONE customers get updated. E.g. for 10 customers, only 9 will get the new address.

If we take the same code but using EF:
```
// set up context with dummy data
...
Context.SaveChanges();

//ef update works fine
foreach (var customer in Context.Customers)
{
    customer.ADDRESS_ID = "some other value";
}
```
All customers are updated.

### Code
Upon looking at the source code, it seems that in April 2019 there was a change to [BatchUpdate](https://github.com/zzzprojects/EntityFramework-Plus/commit/3d115f0d0c4c6e3f7f44bbcc1d1585e2f91a574e#diff-4646fb689b7a5d3366977ee8c39cc3c7) with renaming context to queryContext and attaching entity to a duplicate context.

I have managed to fix the issue for myself locally by attaching the entity to queryContext instead, but I am sure there was a reason behind this code which I dont know.

### Further technical details
With real database it seems to work fine. Regular simple props also seem to work fine.
- EF version: EF Core 2.2.6
- EF Plus version: 2.0.22
- Database Provider: Oracle

**Comment by JonathanMagnan** [comment] 2019-11-12 18:12
Hello @MirandaDotNet ,

Thank you for reporting,

We will look at this.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by MirandaDotNet** [comment] 2019-11-13 07:33
Thanks, Jonathan.
Later I have also noticed similar problems with batch delete and in memory db:
When batch deleting records that have some relation in db context and then do Context.SaveChanges, it will throw an exception : 

**Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException : Attempted to update or delete an entity that does not exist in the store.**

EF Context.RemoveRange + Context.SaveChanges works fine.

Regards,
Marina

**Comment by JonathanMagnan** [comment] 2019-11-19 02:07
Hello @MirandaDotNet ,

We started to look at this issue.

My developer took some time but it seems we are missing something to reproduce it.

Do you think you could provide a project sample with this issue?

**Comment by MirandaDotNet** [comment] 2019-11-19 11:59
Hi, @JonathanMagnan ,
I have attached a test solution with different examples.
[TestBatchEF.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/3863614/TestBatchEF.zip)

For our purposes I have assembled the library locally, with a change in BatchUpdate and BatchDelete methods to save source context instead of a cloned one. I do not expect a performance gain from in memory batch operations anyway, so the fix worked for us.

Thanks in advance!

**Comment by JonathanMagnan** [comment] 2019-12-17 19:05
Hello @MirandaDotNet ,

Sorry for the long waiting.

The fix has been finally released in the v3.0.31

If you have the chance to try it, let us know if that fix worked as expected.

**Comment by MirandaDotNet** [comment] 2019-12-18 13:20
Thanks! Will check that out!

**Comment by MirandaDotNet** [comment] 2019-12-26 13:59
Hi, Jonathan,
It seems that something else got broken - Update doesn't work at all - no props are updated.
From my test project:

```
 [Fact]
        public void TestInMemoryBatchUpdate()
        {
            //this is fine - for straightforward update for entities that don''t have navigation props
            _context.Addresses.AsQueryable().Update(x => new Address { AddressLine = "dummy" });

            Assert.True(_context.Addresses.ToList().All(x => x.AddressLine == "dummy"));
        }
```

This fails.

Also note that comparing to my initial version of test proj, I had to call **ToList()**. It seems that after 
 __context.Addresses.AsQueryable().Update(_  something is off with context entities, because regular All (__context.Addresses.All(x => x.AddressLine == "dummy")_) would return true.

(version 2.0.31 or 3.0.31)

**Comment by JonathanMagnan** [comment] 2020-01-03 16:50
Hello @MirandaDotNet ,

We believe it currently happens because you do not re-use the same memory database and the context from `ContextFactory` must be used with the same.

For example: 
```csharp
var guid = Guid.NewGuid();
EntityFrameworkManager.ContextFactory = dbContext => { return new InMemoryContext(guid); };
_context = new InMemoryContext(guid);


public class InMemoryContext : DbContext
{
	public InMemoryContext(Guid guid) : base(new DbContextOptionsBuilder<InMemoryContext>().UseInMemoryDatabase(guid.ToString()).Options)
	{
	}
}
```

If you still have an issue, please provide us a small runnable project and we will fix it to make it work with the InMemory provider.

**Comment by MirandaDotNet** [comment] 2020-01-06 09:47
Hi @JonathanMagnan ,
I must admit I do not know how re-using the context might affect things in my case. Context is created with random guid everytime the test runs on purpose - to test the isolated cases for tests. Even if i comment out all the tests and leave one failing test - it would still fail.

Nevertheless, I did as you suggested and it is still not working:

`
  public BatchTest()
        {
            Guid guid = Guid.NewGuid();
            EntityFrameworkManager.ContextFactory = context => new InMemoryContext(guid);

            _context = new InMemoryContext(guid);
            _context.Customers.Add(new Customer
            {
                Id = 1,
                Address = new Address
                {
                    Id = 10,
                    AddressLine = "address"
                }
            });

            _context.Addresses.Add(new Address
            {
                Id = 20,
                AddressLine = "other address"
            });

            _context.SaveChanges();
        }

        [Fact]
        public void TestInMemoryBatchUpdateNavigationProps()
        {
            //for entities with navigation props test fails
            var otherAddress = _context.Addresses.First(x => x.Id == 20);
            _context.Customers.AsQueryable().Update(x => new Customer { AddressId = otherAddress.Id});

            Assert.True(_context.Customers.ToList().All(x => x.AddressId == otherAddress.Id && x.Address == otherAddress));
        }
`

Please note my previous comment - it is very fishy that I HAD to call ToList before calling ALL. Otherwise the test would succeed! In regular behavior for Queryable All automatically calls enumeration, but not in this case.

I have also tried the following (resetting navigation props explicitly) and it worked. The same solution for the case that I have reported initially: 

`
 [Fact]
        public void TestInMemoryBatchUpdateNavigationProps()
        {
            //for entities with navigation props test fails
            var otherAddress = _context.Addresses.First(x => x.Id == 20);

            foreach (var contextCustomer in _context.Customers)
            {
                contextCustomer.Address = null;
            }

            _context.SaveChanges();

            _context.Customers.AsQueryable().Update(x => new Customer { AddressId = otherAddress.Id});

            Assert.True(_context.Customers.ToList().All(x => x.AddressId == otherAddress.Id && x.Address == otherAddress));
        }
`

I would very much appreciate feedback on this issue of mine. Right now I resorted to using old version of the lib fixed locally.

Thanks in advance!

**Comment by JonathanMagnan** [comment] 2020-01-06 21:45
Hello @MirandaDotNet ,

## AsNoTracking
The `Update` method performs the operation directly in the database (or memory). However, the local item is not modified.

Since the item has been modified in the database, you need to use the `AsNoTracking`, otherwise the local item will be taken

```csharp
Assert.True(_context.Customers.AsNoTracking().ToList().All(x => x.AddressId == otherAddress.Id  ));
```

## Reference
In addition to the `AsNoTracking`, you cannot compare the reference (due to the `AsNoTracking`). That's why the `x.Address == otherAddress` has been removed.

Another technic would be to don't materialize the entity as you have said. Since when you don't materialize entities, it doesn't take those in local but entities in memory instead

```csharp
Assert.True(_context.Customers.All(x => x.AddressId == otherAddress.Id ));
```

## Example
Here is a project that my developer has made:
[TestBatchEF (2).zip](https://github.com/zzzprojects/EntityFramework-Plus/files/4027906/TestBatchEF.2.zip)

Let me know if that helps you a little ;)

**Comment by MirandaDotNet** [comment] 2020-01-08 10:36
Hi @JonathanMagnan ,
Yes, your example seems to work. I understand that the action is performed directly on db, but one of the old versions for inmemory also updated the item, that is why I got confused.

Technically for us, it is either all functionality to be moved to batch operations or none. Previously we managed to juggle between context and direct db related operations.

Thanks!

**Closed** 2020-01-16 13:17 UTC
