### ISSUE TITLE
Query Cache Bug

### ISSUE THREAD

**Issue by jx-qyj** [zzzprojects/EntityFramework-Plus#4] opened 2016-04-14 06:36 UTC
Hello, I ask why (Query Cache Entity Framework) to add the data can not immediately update the cache?

**Comment by zzzprojects** [comment] 2016-04-14 11:38
I’m not sure to understand the question.

Do you want an overloaded method which allows forcing to update the cache?

**Example**

```
// Cache data
var countries1 = ctx.Countries.FromCache().ToList();

// FORCE the cache to be updated
var countries2 = ctx.Countries.FromCache(true);
```

**Comment by zzzprojects** [comment] 2016-05-11 16:48
Closing issue due to no answer and bug fixed in unit tests

(Probably duplicate of: https://github.com/zzzprojects/EntityFramework-Plus/issues/5)

**Closed by zzzprojects** 2016-05-11 16:48 UTC

**Comment by jx-qyj** [comment] 2016-05-12 00:26
@zzzprojects  Thank you, I have resolved
