### ISSUE TITLE
UpdateAsync not updating when using Task.WaitAll

### ISSUE THREAD

**Issue by MaklaCof** [zzzprojects/EntityFramework-Plus#208] opened 2017-08-15 10:05 UTC
I try this code, but it is not working:
```
foreach (var item in updates)
                tasks.Add(this.context.ConfigurationParameters
                    .Where(t => t.ConfigurationId == ConfigurationId && t.ParameterId == item.Key)
                    .UpdateAsync(t => new DbConfigurationParameter() { ParameterValueId = item.Value, Level = -3 }));
            Task.WaitAll(tasks.ToArray());

```
but this does:
```
foreach (var item in updates)   //we must do this after save changes, otherwise nothing is updated
                await this.context.ConfigurationParameters
                    .Where(t => t.ConfigurationId == ConfigurationId && t.ParameterId == item.Key)
                    .UpdateAsync(t => new DbConfigurationParameter() { ParameterValueId = item.Value, Level = -3 });

```
Did I do something wrong?

**Comment by JonathanMagnan** [comment] 2017-08-15 10:57
Hello MaklaCof,

What do you mean by `it is not working`?

You get an error on it simply doesn't execute?

Best Regards,

Jonathan

**Comment by MaklaCof** [comment] 2017-08-15 11:40
Changes are not in database. No error. But if I debug (run step by step), changes are in database.

**Comment by JonathanMagnan** [comment] 2017-08-15 12:38
Hello @MaklaCof ,

I'm not sure why you don't get an error but you probably get one.

Anyway, you should not use `Task.WaitAll` in this kind of scenario. The problem is you try to execute multiple query at the same time from the same context which may lead to some concurrency error like opening/closing connection.

You will get the same error without using our library.

By example:

```csharp
var task1 = ctx.Activities.Where(x => x.ColumnInt == 1).ToListAsync();
var task2 = ctx.Activities.Where(x => x.ColumnInt == 2).ToListAsync();
var task3 = ctx.Activities.Where(x => x.ColumnInt == 3).ToListAsync();

Task.WaitAll(task1, task2, task3);
```

Will throw the following error:

> System.NotSupportedException: 'A second operation started on this context before a previous asynchronous operation completed. Use 'await' to ensure that any asynchronous operations have completed before calling another method on this context. Any instance members are not guaranteed to be thread safe.'

So, you should always use the second example you provide with `await` to make sure only one execute using the same context is done at a time.

Another way to `fix it` is creating a new context for every task to allow them to be executed at the same time.

Let me know if that's clearer why this is happening.

Best Regards,

Jonathan

**Closed** 2017-08-15 18:11 UTC
