### ISSUE TITLE
Batch Delete often occurs error and stoped 

### ISSUE THREAD

**Issue by viewtance** [zzzprojects/EntityFramework-Plus#205] opened 2017-08-04 09:08 UTC
Sometimes the Batch delete operation failed to execute and throw below exception, then caused my application crashed, and the delete action is scheduled daily, if one if them failed, it will not delete them, is there a mechanism avoid the error occur and make sure delete action successfully executed?

BTW, it is running with EF Core.

`Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Data.SqlClient.SqlException
   at System.Data.SqlClient.SqlConnection.OnError(System.Data.SqlClient.SqlException, Boolean, System.Action`1<System.Action>)
   at System.Data.SqlClient.SqlInternalConnection.OnError(System.Data.SqlClient.SqlException, Boolean, System.Action`1<System.Action>)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(System.Data.SqlClient.TdsParserStateObject, Boolean, Boolean)
   at System.Data.SqlClient.TdsParser.TryRun(System.Data.SqlClient.RunBehavior, System.Data.SqlClient.SqlCommand, System.Data.SqlClient.SqlDataReader, System.Data.SqlClient.BulkCopySimpleResultSet, System.Data.SqlClient.TdsParserStateObject, Boolean ByRef)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(System.Data.SqlClient.SqlDataReader, System.Data.SqlClient.RunBehavior, System.String, Boolean, Boolean)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(System.Data.CommandBehavior, System.Data.SqlClient.RunBehavior, Boolean, Boolean, Int32, System.Threading.Tasks.Task ByRef, Boolean, Boolean, System.Data.SqlClient.SqlDataReader, Boolean)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(System.Data.CommandBehavior, System.Data.SqlClient.RunBehavior, Boolean, System.String, System.Threading.Tasks.TaskCompletionSource`1<System.Object>, Int32, System.Threading.Tasks.Task ByRef, Boolean ByRef, Boolean, Boolean)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(System.Data.CommandBehavior, System.Data.SqlClient.RunBehavior, Boolean, System.String)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Z.EntityFramework.Plus.BatchDelete.Execute[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Linq.IQueryable`1<System.__Canon>)
   at Z.EntityFramework.Plus.BatchDeleteExtensions.Delete[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Linq.IQueryable`1<System.__Canon>, System.Action`1<Z.EntityFramework.Plus.BatchDelete>)
   at Z.EntityFramework.Plus.BatchDeleteExtensions+<>c__DisplayClass2_0`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<DeleteAsync>b__0()
   at System.Threading.Tasks.Task`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Viewtance.MES.EntityFrameworkCore.Repositories.Report.Processes.AR.RecordRecentRepository+<BatchDeleteAsync>d__4.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Abp.Threading.InternalAsyncHelper+<AwaitTaskWithPostActionAndFinally>d__1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Viewtance.Report.Core.Domain.Processes.AR.RecordRecentManager+<DeleteRecent>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Abp.Threading.InternalAsyncHelper+<AwaitTaskWithPostActionAndFinally>d__1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Viewtance.Report.Core.Domain.Processes.AR.RecordRecentManager+<>c__DisplayClass4_0+<<MoveRecentToHistory>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

`

**Comment by JonathanMagnan** [comment] 2017-08-04 13:05
Hello @viewtance ,

Thank you for reporting,

We will soon investigate this issue very soon.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-08-07 18:17
Hello @viewtance ,

I have done some research about this error. I may be wrong but I don't believe this problem is caused by our library.

Currently, it could be almost anything like by example a network issue, deadlock, or something else.

Is it possible for you to log the error including inner exception?

Best Regards,

Jonathan

**Comment by viewtance** [comment] 2017-08-10 05:17
@JonathanMagnan Thanks for your investigation, observe the exception logs several days, I found only the above reported background worker occurred this error, others works fine, it maybe caused by my code or the data. I will try to figure out the reasons behind.

**Comment by JonathanMagnan** [comment] 2017-08-10 13:15
Hello @viewtance ,

I will close this issue since I don't think it's related to our library, but if you have more information, feel free to reopen it.

There are several scenarios that can cause this issue, by example, do the SQL Server has been restarted? The server itself? It's possible that the network connection dropped 1s? Etc... I'm not exactly sure if the same error will be raised but looking on Google, it might be hard to find the real cause.

Best Regards,

Jonathan

**Comment by viewtance** [comment] 2017-08-12 07:52
@JonathanMagnan I don't think you listed possible causes are the potential reasons, because I found on another deployed application, it still throw this exception, but it is not the previous background worker, it is another one and with the same exception, it may be caused by the data, not is the code.

Could you give me more suggestions that what scenario will let sql server throw such exception when do a batch deletion action?

**Comment by JonathanMagnan** [comment] 2017-08-12 10:22
Hello @viewtance ,

Do the other code also use Batch Delete on the line that fail?

Honestly, you will get a better idea of what cause this by looking on google:
https://www.google.ca/search?q="The+process+was+terminated+due+to+an+unhandled+exception."+%2B+"Exception+Info%3A+System.Data.SqlClient.SqlException"+%2B+"OnError"

Best Regards,

Jonathan

**Comment by viewtance** [comment] 2017-08-12 17:06
@JonathanMagnan , Yes, there are more than 40 background workers do the similar batch deletion on night in my application, others work fine, so far, on 2 different deployments, via the log check I found it often occurs the same exception on 2 different background worker. 

Before then, I was use EF core to do the deletion, 3 thousand records needs to take more than 3 hours to be deleted, but it could delete them successfully even need to spend so much time.

I will take a try that replace the Batch Delete with a raw SQL delete, to see if it could works as expected.

**Comment by JonathanMagnan** [comment] 2017-08-12 18:17
Hello @viewtance ,

Could you check if there is a deadlock error in your log on this table?

I'm currently working on adding an option to fix this kind of error. It will probably be released tomorrow so I will be able to give you more information about it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-08-14 15:24
Hello,

The v1.6.10 has been released (release note)

The options “UseTableLock” has been added.

When enabled, the table will be locked instead of row/index, perhaps if you had a deadlock error, that could fix your problem.

```csharp
ctx.Activities.Where(a => a.DateCreated < d).Delete(delete => delete.UseTableLock = false );
```

Let me know if that fixed your issue.

Best Regards,

Jonathan

**Comment by viewtance** [comment] 2017-09-07 11:29
@JonathanMagnan Sorry for so long time get back to you, I was not check if there was a deadlock error on SQL Server log, but after upgrade to version 1.6.10, the error not happen again. I think the "UseTableLock" should fixed my issue. 
Thanks a lot for your effort.

**Comment by JonathanMagnan** [comment] 2017-09-07 12:34
No problem ;)

Closing Comment: Fix confirmed

**Closed by JonathanMagnan** 2017-09-07 12:34 UTC
