### ISSUE TITLE
EF Batch Update - query after batch update does not contain the changes

### ISSUE THREAD

**Issue by adrianwright** [zzzprojects/EntityFramework-Plus#274] opened 2017-11-17 16:10 UTC
I have observed that EF Batch Update changes do not appear to be available via query during a transaction. For example:
1. Insert a record
2. Call context.SaveChanges()
3. Run a batch update that affects your record.
4. Call context.SaveChanges()
5. Query your object and you observe that the change has not been made.
 
However, the change is made when the transaction is committed. 

Is this expected?

**Comment by JonathanMagnan** [comment] 2017-11-19 15:55
Thank you for reporting.

I successfully reproduced this issue.

I don't understand why this is happening. It's certainly not expected.

I will try to figure out what we are missing.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-12-01 20:12
Hello @adrianwright ,

Sorry for the delay.

I confirm you `BatchUpdate` work well with a transaction. However, the behavior is a little bit differently.

It appears the error is due how the ChangeTracker work and doesn't reload existing entities.

If you take the code below,

- `var list = context.EntitySimples.ToList();` will return 2 entities but the first entity still have the value `IntColumn = 1`
- `var listNoTracking = context.EntitySimples.AsNoTracking().ToList();` will return 2 entities and the first entity have the value `IntColumn = 10`

It looks like the entities is already part of the change tracker, even if value has been modified, entity value is not updated.

```csharp
var transaction = context.Database.BeginTransaction();

// 1. Insert a record
context.EntitySimples.Add(new EntitySimple() { IntColumn = 1 });

// 2.Call context.SaveChanges()
context.SaveChanges();

// 3.Run a batch update that affects your record.
context.EntitySimples.Update(x => new EntitySimple() {IntColumn = 10});

// 4.Call context.SaveChanges()
context.EntitySimples.Add(new EntitySimple() { IntColumn = 2 });
context.SaveChanges();

// 5.Query your object and you observe that the change has not been made.
var list = context.EntitySimples.ToList();
var listNoTracking = context.EntitySimples.AsNoTracking().ToList();
transaction.Rollback();

var listAfter = context.EntitySimples.ToList();
```

You can easily reproduce the same error without transaction, with breakpoint and SQL statement
```sql
UPDATE dbo.Z_EntityFramework_Plus_Lab_Form_Request_BatchUpdate_WithTransaction_EntitySimple
SET IntColumn = 2303
```

One will contain original value from the change tracker and the `AsNoTracking` will have database values.

Let me know if that explains correctly the current behavior.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by adrianwright** [comment] 2017-12-01 20:42
Thanks for the investigation. It sounds like this is expected behavior?

**Comment by JonathanMagnan** [comment] 2017-12-01 21:56
Yup, this is the expected behavior how the `ChangeTracker` work.

You can get a similar result using a breakpoint and make change directly in the database.

- if entities returned are tracked, value are not updated
- if entities returned are NOT tracked, new entities with database values are created.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment] 2017-12-13 20:00
Hello @adrianwright ,

We are currently making some issue cleanup.

Feel free to reopen if you believe we closed it by mistake

Best Regards,

Jonathan


---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Closed by JonathanMagnan** 2017-12-13 20:00 UTC
