### ISSUE TITLE
No IncludeFilter tests for EF Core 2.0

### ISSUE THREAD

**Issue by aadhoc** [zzzprojects/EntityFramework-Plus#279] opened 2017-11-30 16:09 UTC
For EF Core 2.0, it appears that the conditional pragmas are disabling all code in IncludeFilter.cs.
(Does the IncludeFilter actually work in EF Core?)

I'm having problems getting IncludeFilter extensions to register with EF Core 2.0, so I downloaded the project and looked into the test project.

I found that the `Z.Test.EntityFramework.Plus.EFCore` project defines compilation symbols: `EFCORE FULL`

Yet `src\test\Z.Test.EntityFramework.Plus.EFCore\QueryCache\WithInclude\IncludeFilter` has:
```
#if EF6

using System.Collections.Generic;
using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Z.EntityFramework.Plus;

namespace Z.Test.EntityFramework.Plus
{
    public partial class QueryCache_WithInclude
    {
        [TestMethod]
        public void IncludeFilter()
        {
            [..]
        }
    }
}
#endif
```
Tried the following two options which enable the `IncludeFilter.cs` test:

- Change compilation symbols to: `EFCORE FULL EF6` (breaks the test build)
- Change the IncludeFilter.cs `#if EF6` to `#if EFCORE` (breaks the test build)

**Comment by JonathanMagnan** [comment] 2017-11-30 16:18
Hello @aadhoc ,

Unfortunately, we cannot release this feature until the EF Core team fix the N+1 query with anonymous types.

You can find a longer description of the issue here: https://stackoverflow.com/a/43472202/5619143

Let me know if that successfully answer the problem and if we can close this issue.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by aadhoc** [comment] 2017-11-30 18:12
Just to verify... the recent 2.0.1 update is still inadequate?

Thanks for the quick reply.

**Comment by JonathanMagnan** [comment] 2017-11-30 19:28
I will try to investigate this during the weekend.

I tried to create a `non-working` scenario but it works...

Long time I didn't check it so I may miss something important.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment] 2018-03-04 21:30
Just to give an update since I forget to answer.

Unfortunately yes, 2.0.1 is still inadequate.

There is still issue with the projection that doesn't allow us to support it yet.

Best Regards,

Jonathan

**Comment by mhosman** [comment] 2018-06-09 18:38
How about now with 2.1 release???

**Comment by mhosman** [comment] 2018-06-11 01:46
Now supports N+1 queries

**Comment by JonathanMagnan** [comment] 2018-06-11 02:57
Hello @mhosman ,

I'm not sure to understand your last comment. The `N+1` queries was always supported by EF Core and that's the cause why we cannot do that features yet.

When using a projection with a filter

```csharp
var parents = ctx.Parents
    .Select(x => new
    {
        parent = x,
        Child = x.Childs.Where(y => y.ColumnInt > 2)
    })
    .ToList();
```

Only the parent is evaluated and child is resolved one by one later which cause the N+1 queries. So it leads to VERY bad performance.

That problem is the reason why we "cannot" support it yet and is still happening in the v2.1

Under the hood, our library does a projection with a filter so I believe releasing a feature that causes a N+1 queries will be way worse than not releasing it.

Let me know if that explains correctly why we still don't support it.

Best Regards,

Jonathan

**Comment by cgountanis** [comment] 2019-05-30 20:07
I love this idea, any clue when this will be available? I have a need to join many tables and filter the children with ease/performance in mind.

**Comment by JonathanMagnan** [comment] 2019-05-30 21:12
Hello @cgountanis ,

As said, I don't think we plan to release that features (has been coded/worked on our side since v1.x...) if that's going to create n+1 queries.

The following code

```csharp
var parents = ctx.Parents
	.Select(x => new
	{
		parent = x,
		Child = x.Childs.Where(y => y.ColumnInt > 2)
	})
	.ToList();

var childs = parents.SelectMany(x => x.Child).ToList();
```

Will execute a query for every parent when you retrieve children. Our library use under the hood projection which works perfectly in `EF6` and [EF Classic](https://entityframework-classic.net/) but not in EF Core.

Releasing this feature will just add so many performance issues for people that use it and unaware of this limitation.

I do not have honestly great hope that **MAJOR** issue will be fixed anywhere soon: https://github.com/aspnet/EntityFrameworkCore/issues/10001#issuecomment-456581915

**Comment by cgountanis** [comment] 2019-05-31 15:04
Thanks for the heads up. By not using ToList (obvious no-no) right away I was able to add to the query within the repository before it executes in the controller. It seems to be smart enough to keep it down to a single query. We found a great way to break up the table calls to better the API although, yes, runs more than one query but gives us more power from an API standpoint. I will keep a lookout for the Core release on this.

**Comment by JonathanMagnan** [comment] 2019-05-31 15:16
Looking at your message,

We could perhaps check how we could do it differently, a little bit more like the `IncludeOptimized` in EF6.

If we use how the ChangeTracker work behind the hood, we could easily transform the previous query to something similar to this:

```csharp
var parentsFuture = ctx.Parents.Future();
ctx.Parents.SelectMany(x => x.Childs).Where(y => y.ColumnInt > 2).Future();

var parents = parentsFuture.ToList();
```

It throws 2 queries (one round-trip) and return all parents which their childs populated as we would expect. Will not work with `AsNoTracking` but I believe that's fine.

I don't remember why we didn't go using this logic for EF Core, I guess we will investigate it and see what's the limitation using this logic instead of waiting that projection get fixed.

I will keep you updated.

**Comment by JonathanMagnan** [comment] 2019-06-06 18:13
Hello,

Good news, a new version is now available v1.10.0

We added in this version the support to `QueryFilter` for EF Core 2.x
It also works with the non-async method in EF Core 3.x

The support for 3.x will be soon available. We are currently in discussion about how we should release it since we cannot anymore support both versions at the same time (There is some breaking change in EF Core interface used by QueryFilter).

Please confirm us that everything works as expected.

**Comment by JonathanMagnan** [comment] 2019-06-14 14:51
Did anyone get the chance to try it?

We would really love to get feedback on this one

**Closed** 2019-06-30 14:26 UTC

**Comment by vertonghenb** [comment] 2019-08-25 11:37
@JonathanMagnan Is there a daily build after preview-8 we can try it with? In P8 the feature is disabled which makes it unusable.

**Comment by JonathanMagnan** [comment] 2019-08-25 15:05
Hello @vertonghenb ,

I believe we didn't make it since my developer got a few issues when trying to reference the latest daily build.

If you can send us a console application project that uses the latest EF Core version then we will be happy to check it and make it compatible. The project can just do a simple select in EF Core, that will be enough ;)

You can attach the project here or send it to info@zzzprojects.com
