### ISSUE TITLE
After version 1.6.18 batch deletion action failed

### ISSUE THREAD

**Issue by viewtance** [zzzprojects/EntityFramework-Plus#237] opened 2017-09-15 03:39 UTC
After updated to version 1.6.19 and 1.6.20, the batch deletion action never run successfully, it crashed the application and below is the exception log which recorded by OS:

BTW, the EF core version is 2.0.

`Application: MES.Web.Host.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Collections.Generic.KeyNotFoundException
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Item(System.__Canon)
   at Z.EntityFramework.Plus.BatchDelete.CreateCommand(System.Linq.IQueryable, Microsoft.EntityFrameworkCore.Metadata.IEntityType)
   at Z.EntityFramework.Plus.BatchDelete.Execute[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Linq.IQueryable`1<System.__Canon>)
   at Z.EntityFramework.Plus.BatchDeleteExtensions.Delete[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Linq.IQueryable`1<System.__Canon>, System.Action`1<Z.EntityFramework.Plus.BatchDelete>)
   at Z.EntityFramework.Plus.BatchDeleteExtensions+<>c__DisplayClass2_0`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<DeleteAsync>b__0()
   at System.Threading.Tasks.Task`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at MES.EntityFrameworkCore.Repositories.Report.Processes.MSCache.RGV.EquipmentStateRecentRepository+<BatchDeleteAsync>d__4.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Abp.Threading.InternalAsyncHelper+<AwaitTaskWithPostActionAndFinally>d__1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Report.Core.Domain.Processes.MSCache.RGV.EquipmentStateRecentManager+<DeleteRecent>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Abp.Threading.InternalAsyncHelper+<AwaitTaskWithPostActionAndFinally>d__1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Report.Core.Domain.Processes.MSCache.RGV.EquipmentStateRecentManager+<>c__DisplayClass4_0+<<MoveRecentToHistory>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

`

**Comment by JonathanMagnan** [comment] 2017-09-15 16:26
Hello @viewtance ,

Thank you for reporting,

We will for sure look at it during the weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-09-23 23:16
Hello @viewtance ,

Do you think you could reproduce this issue using the following example?

We are currently unable to reproduce it and since it seems to have an issue with a dictionary (we don't use any in our code I believe), it makes quite hard to reproduce it.

```csharp
using System.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Z.Test.EntityFramework.Plus;

namespace Z.EntityFramework.Plus.Lab.EFCore20
{
    public class Request_BatchDelete_WhereIgnored
    {
        public static void Execute()
        {
            // CLEAN
            using (var context = new EntityContext())
            {
                context.EntitySimples.RemoveRange(context.EntitySimples);
                context.SaveChanges();
            }

            // SEED
            using (var context = new EntityContext())
            {
                context.EntitySimples.Add(new EntitySimple {IntValueToDelete = 1});
                context.EntitySimples.Add(new EntitySimple {IntValueToDelete = 2});
                context.EntitySimples.Add(new EntitySimple {IntValueToDelete = 1});
                context.SaveChanges();
            }

            // TEST
            using (var context = new EntityContext())
            {
                context.EntitySimples.Delete();
            }
        }

        public class EntityContext : DbContext
        {
            public DbSet<EntitySimple> EntitySimples { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseSqlServer(new SqlConnection(My.Config.ConnectionStrings.TestDatabase));

                base.OnConfiguring(optionsBuilder);
            }
        }

        public class EntitySimple
        {
            public int ID { get; set; }

            public int IntValueToDelete { get; set; }
        }
    }
}
```

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-10-17 00:49
Hello @viewtance ,

We will need to close this issue since no additional information has been provided.

If you can provide an example, please reopen the issue.

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2017-10-17 00:49 UTC

**Comment by Coder3333** [comment] 2018-04-10 13:51
Here is the stack trace that I get with Z.EntityFramework.Plus.EFCore (1.6.20).  I only get this if the query that I call Delete on first uses the query.FromSql command to create a query from a sql string.  As long as I do not use FromSql, everything works fine.  Should I expect Delete to work in conjunction with FromSql generated queries?

   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Z.EntityFramework.Plus.BatchDelete.CreateCommand(IQueryable query, IEntityType entity)
   at Z.EntityFramework.Plus.BatchDelete.Execute[T](IQueryable`1 query)

**Comment by JonathanMagnan** [comment] 2018-04-10 13:54
Hello @Coder3333 ,

Could you create your own thread? It makes easier to follow request. Also, could you try using the latest version?

If you still have the issue, do you think you could provide us a test project with this issue?

It will make easier/faster for my developer to getting started for investigating it.

_We now always ask for a project since we found out that most issues are missing some essential information or are resolved by the requestor when creating it_

_(Even if the issue seem very easy to reproduce, by getting a test project, it allow us to give a faster support and better experience for the support of all our free libraries)_

Best Regards,

Jonathan
