### ISSUE TITLE
Time-out when adding one more IncludeFilter call

### ISSUE THREAD

**Issue by MrYossu** [zzzprojects/EntityFramework-Plus#439] opened 2018-12-05 18:29 UTC
I have the following code in a method...

      return objectSet
        .IncludeFilter(plt => plt.PartInformationTypes.Where(pit => pit.Active))
        .IncludeFilter(plt => plt.PPILookupValues.Where(plv => plv.Active))
        .Where(plt => plt.Active);

..and this returns the data pretty quickly. `objectSet` is an `ObjectSet<PPILookupType>`, and there are 59 of these that have Active set to true. Those 59 reference a mere 248 `PPILookupValues` so the query doesn't take much time.

I now want to include an extra entity in the query, so added one more line...

      return objectSet
        .IncludeFilter(plt => plt.PartInformationTypes.Where(pit => pit.Active))
        .IncludeFilter(plt => plt.PPILookupValues.Where(plv => plv.Active))
        .IncludeFilter(plt => plt.PPILookupValues.Where(plv => plv.Active).Select(plv => plv.PhysicalPartInformations))
        .Where(plt => plt.Active);

However, when I run this, I get a time-out exception. The number of `PhysicalPartInformations` rows referenced is about 53000, which shouldn't cause a problem.

Anyone any idea why this times out, and what I can do about it?

Thanks

**Comment by JonathanMagnan** [comment] 2018-12-05 18:40
Hello @MrYossu ,

The timeout might be due to either the SQL query statement or how EF `6.2` handle some relation in the Change Tracker.

First, could you try directly the SQL Query (without EF) to verify the time it takes to execute and return the result

Best Regards,

Jonathan

**Comment by MrYossu** [comment] 2018-12-05 20:56
Thanks for the reply. I'm using EF 6.0 by the way.

I couldn't see a way to get the SQL that the query generated, as the usual way of doing this (see [this SO answer](https://stackoverflow.com/a/1412902/706346)) gave the following exception...

_System.InvalidCastException: 'Unable to cast object of type 'Z.EntityFramework.Plus.QueryIncludeFilterParentQueryable`1[VisionRT.CRM.Entities.PPILookupType]' to type 'System.Data.Entity.Core.Objects.ObjectQuery'.'_

However, I tried the following Linq in LinqPad...

    PPILookupTypes.Where(t => t.Active)
      .Select(t => new {
        PType = t,
        Values = new {
          Values = t.PPILookupTypePPILookupValues.Where(v => v.Active),
          PPIs = t.PPILookupTypePPILookupValues.Where(v => v.Active).Select(v => v.PPILookupValuePhysicalPartInformation)
        }
      })

...and it ran in 0.007 seconds!

Don't know if that helps. Thanks again.

**Comment by JonathanMagnan** [comment] 2018-12-06 00:03
If you are using SQL Server, you can use the SQL Profiler to take the query that's returned.

About LinqPad, I believe you might have forgotten to perform a `ToList()`

**Comment by MrYossu** [comment] 2018-12-06 13:53
I tried using the profiler, but it cuts off the query text after a certain point, so I couldn't see the full query.

As for calling .ToList(), you're right I forgot! However, even with that in, it only took .5 seconds, so still a long way short of the time out.

Thanks again, any other ideas?

**Comment by JonathanMagnan** [comment] 2018-12-06 20:06
I'm not sure but your issue might be similar to this one: https://github.com/aspnet/EntityFramework6/pull/412

The fix is merged in "dev" branch but not released yet.

The issue was, in short, causing a method to be called billion of time instead of thousands of time.

One way to test it is trying this scenario with `EF Classic` + `Include Filter`. The fix is already done in this version.

- EF Classic: https://entityframework-classic.net/
- EF Plus Filter: https://www.nuget.org/packages/Z.EntityFramework.Plus.QueryIncludeFilter.EFClassic/

Even if you don't plan to use it, at least you will know if that's the cause of the issue or not.

**Comment by JonathanMagnan** [comment] 2018-12-06 20:47
Hello @MrYossu ,

If the issue is caused by this: https://github.com/aspnet/EntityFramework6/pull/412

I cannot have a release date since the issue is inside Entity Framework and there is nothing we can do for it. All we can do is to wait until `Microsoft` release their new version in around 6 months.

In fact, the fix is made on our side in `EF Classic` which we can control the source.

You can also try to change all yours `IncludeFilter` by `IncludeOptimized`, perhaps it will work better with your scenario.

**Comment by MrYossu** [comment] 2018-12-09 16:09
Hello @JonathanMagnan 

Sorry, I misunderstood you, I thought you meant that a new version of your project was in prerelease, didn't realise yours was so closely tied to the EF releases.

I tried changing to IncludeOptimized, but this gave a compiler error. Any idea why? It compiled fine with IncludeFilter.

Thanks again.

**Comment by JonathanMagnan** [comment] 2018-12-10 12:17
What's the compilation error?

**Comment by MrYossu** [comment] 2018-12-10 14:14
@JonathanMagnan Sorry, should have mentioned that!

It was "Cannot resolve symbol IncludeOptimized"

**Comment by JonathanMagnan** [comment] 2018-12-11 01:21
Hello @MrYossu ,

I'm not sure that's related to our library. That kind of issue look more related to `Visual Studio` or `ReSharper` : https://stackoverflow.com/questions/15713167/resharper-cannot-resolve-symbol-even-when-project-builds

Sometimes restarting VS could make it work.

If you believe that's our library, please provide us a sample project with that issue.

**Comment by MrYossu** [comment] 2018-12-11 14:40
Hello again,

I managed to reproduce the behaviour in a sample project, and it shows as an error even if R# is disabled.

Before I post the solution, let me check I'm doing this right...

I started a new console app, and added a Nuget reference to Z.EntityFramework.Plus.QueryIncludeFilter.EF6 version 1.7.11, then added an EF model and used the code I showed at the beginning.

With IncludeFilter it compiles (and runs extremely quickly, so I can't reproduce the issue I came here to resolve), but if I change that to IncludeOptimized I get the compiler error.

Should that have worked, or have I done something stupid already? If this sounds right, I'll package it up and make it available so you can see what's going on.

Thanks again

**Comment by JonathanMagnan** [comment] 2018-12-11 14:57
Hello @MrYossu ,

You need to either use the package with all features: https://www.nuget.org/packages/Z.EntityFramework.Plus.EF6/

Or add as reference the package with QueryIncludeOptimized: https://www.nuget.org/packages/Z.EntityFramework.Plus.QueryIncludeOptimized.EF6/

Just to let you know, standalone package are no longer up to date, only the packages with all feature (https://www.nuget.org/packages/Z.EntityFramework.Plus.EF6/) contains latest release and fix.

**Comment by MrYossu** [comment] 2018-12-11 18:32
Well cut off both my legs and call me Shorty! Thanks for that.

**Comment by JonathanMagnan** [comment] 2018-12-11 19:36
lol no problem ;)

I will close this issue, if you still need help, let me know.

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2018-12-11 19:36 UTC
