### ISSUE TITLE
 QueryFilterManager.InitilizeGlobalFilter throw Exeption

### ISSUE THREAD

**Issue by refcons** [zzzprojects/EntityFramework-Plus#127] opened 2017-02-16 11:18 UTC
Hello. Im trying to user Query Filter Global in Asp.net Core application for implement SoftDelete.
Im intitialize  Query Filter Global in DbContex ctror:

public SeedworkContext(DbContextOptions<SeedworkContext> options) : base(options)
        {
            QueryFilterManager.Filter<Person>(q => q.Where(x => !x.IsDeleted));

            QueryFilterManager.InitilizeGlobalFilter(this);
        }

The SeedworkContext is created by the IoC with parsmeter ServiceLifetime.Scoped.
I have five different ajax post requests where the SeedworkContext is used.
On the fourth request QueryFilterManager.InitilizeGlobalFilter(this) throw System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=Collection was modified; enumeration operation may not execute.
  Source=System.Private.CoreLib
  StackTrace:
       at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
       at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
       at Z.EntityFramework.Plus.QueryFilterManager.InitilizeGlobalFilter(DbContext context)
       at Reflect.Seedwork.Data.DbContexts.SeedworkContext..ctor(DbContextOptions`1 options) in SeedworkContext.cs:line 24
       at lambda_method(Closure )
       at DryIoc.Scope.TryGetOrAdd(Int32 id, CreateScopedValue createValue)
       at lambda_method(Closure , Object[] , IResolverContext , IScope )
       at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
       at Reflect.Seedwork.Data.UnitOfWork.UnitOfWork.GetOrCreateDbContext[TDbContext]() in UnitOfWork.cs:line 234
       at Reflect.Seedwork.Data.Repository.Repository`3..ctor(IUnitOfWork uow) in Repository.cs:line 30
       at lambda_method(Closure )
       at DryIoc.Scope.TryGetOrAdd(Int32 id, CreateScopedValue createValue)
       at lambda_method(Closure )
       at DryIoc.Scope.TryGetOrAdd(Int32 id, CreateScopedValue createValue)
       at lambda_method(Closure )
       at DryIoc.Scope.TryGetOrAdd(Int32 id, CreateScopedValue createValue)
       at lambda_method(Closure )
       at DryIoc.Scope.TryGetOrAdd(Int32 id, CreateScopedValue createValue)
       at lambda_method(Closure )
       at DryIoc.Scope.TryGetOrAdd(Int32 id, CreateScopedValue createValue)
       at lambda_method(Closure , Object[] , IResolverContext , IScope )
       at DryIoc.Microsoft.DependencyInjection.DryIocServiceProvider.GetRequiredService(Type serviceType)
       at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
       at Microsoft.AspNetCore.Identity.SecurityStampValidator.ValidatePrincipalAsync(CookieValidatePrincipalContext context)
       at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.<HandleAuthenticateAsync>d__12.MoveNext()
  InnerException: 

Help please what could be the problem?

**Comment by JonathanMagnan** [comment] 2017-02-16 12:26
Hello @refcons ,

The `QueryFilterManager.Filter` method is not thread-safe by design. It should be configured only once.

Example when the application starts or in a static constructor of the DbContext.

Otherwise, you are adding a new global filter every time you call the method `SeedworkContext` which may lead to this error.

Example
```csharp
public class CurrentContext : DbContext
{
	static CurrentContext()
	{
		// The filter will be only added once
		QueryFilterManager.Filter(q => q.Where(x => !x.IsDeleted));
	}

	public SeedworkContext(DbContextOptions options) : base(options)
	{
		QueryFilterManager.InitilizeGlobalFilter(this);
	}
}
```

Let me know if I answered your question/issue correctly

Best Regards,

Jonathan

**Comment by refcons** [comment] 2017-02-16 14:06
Many thanks. That solved the problem. But in the process I ran into the following problem. I have a generic IQueryable repository where  use  _dbContext.Set<TEntity>().Select(e=>e). In this case, the filter does not work. 
 var context = SeedworkContextFactory.Create();
            var persons1 = context.Persons.ToList();   --- Filter work fine.
            var psersons2 = context.Set<Person>().ToList();  --- Filter not work
            var persons3 = context.Set<Person>().Select(e => e).ToList();  --- Filter not work

**Comment by JonathanMagnan** [comment] 2017-02-16 14:27
Hello @refcons ,

Are you using EF Core?

Currently, we are waiting until EF Core implement interceptor to automatically filter set.

Meanwhile, you can use the method SetFiltered
```csharp
context.SetFiltered<Customer>.Where(....);
```

Let me know if that's working.

Best Regards,

Jonathan

**Comment by refcons** [comment] 2017-02-16 14:33
Thank you very much. It works perfectly

**Comment by JonathanMagnan** [comment] 2017-02-16 14:34
Closing comment: Fix confirmed

**Closed by JonathanMagnan** 2017-02-16 14:34 UTC
