### ISSUE TITLE
Memory leak with query filters for EF Core

### ISSUE THREAD

**Issue by soniachikh** [zzzprojects/EntityFramework-Plus#507] opened 2019-08-15 12:50 UTC
### Description
We are using EntityFramework-Plus to add query filters, unfortunately since switching to ,net core ( EF Core ) we noticed a continuous increase in memory usage.  
Prefview shows that 99% of the memory is occupied by _CacheWeakFilterQueryable_ .
Here is the code we use :

 DbContext.Filter<OrganizationDetail>(Orgs=> Orgs.Where(x => organizationIds.Contains(x.Id)));

The process has to be restarted so that it does not run out of memory.
The documentation is vague as to what is supported for EF Core.
Is it a known issue? is there a work around?

Thank you

**Comment by JonathanMagnan** [comment] 2019-08-15 13:12
Hello @soniachikh ,

Thank you for reporting.

We will look at it. Perhaps we made a mistake on our side or the `ConditionalWeakTable` doesn't correctly work in .NET Core.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by soniachikh** [comment] 2019-08-15 15:40
@JonathanMagnan  Thank you for the quick response, can you think of a workaround.  Getting rid of this feature implies major changes on our side.  Thank you for your help

**Comment by JonathanMagnan** [comment] 2019-08-15 16:47
Hello @soniachikh ,

We will first check it during this weekend to check if we made a mistake on our side.

We already know some way to do it without having to use the `ConditionalWeakTable` but we want first check the issue.

**Comment by JonathanMagnan** [comment] 2019-08-19 13:29
Hello @soniachikh ,

We investigated a little bit the issue. We found no code on our side yet that could lead to it.

Could you let me know which version of .NET Core you are using before we continue our investigation?

For example, the v2.2 has a fix that could be related to `ConditionalWeakTable`: https://github.com/microsoft/ApplicationInsights-dotnet-server/issues/1187#issuecomment-493780259 (might not be related at all, by knowing the version will help us anyway)

**Comment by soniachikh** [comment] 2019-08-22 14:42
Hi Johnathan, 
Sorry for the delay I was out of office.  We are using the latest stable version of .net core 2.2.0.
When I looked into the conditionalweaktable I find the links you sent but the profiler is disabled.  We see the issue when the number of requests is high and many at the same time ... We see it in our production set up but not in our development env.
The main difference between the 2 environments is traffic ... Let me know if you need mere informations.  We will continue looking into it to provide you more information

**Comment by JonathanMagnan** [comment] 2019-09-04 23:41
Closing,

@soniachikh find out that the issue was caused by the `FromSql` method: https://github.com/aspnet/EntityFrameworkCore/issues/12902

**Closed by JonathanMagnan** 2019-09-04 23:41 UTC
