### ISSUE TITLE
batch update issue

### ISSUE THREAD

**Issue by panizza** [zzzprojects/EntityFramework-Plus#195] opened 2017-07-26 07:59 UTC
Hi, I have a problem with Update method.
I have the following code

 ```csharp
public int UpdateUserConditionally(bool updateStatus, string newStatus,
						      bool updateFirstName, string firstName,
						      bool updateLastName, string lastName)
{
	return context.Users
			.Update(u => new User
			{
				STATUS = updateStatus ? newStatus : u.STATUS,
				FIRST_NAME = updateFirstName ? firstName: u.FIRST_NAME,
				LAST_NAME = updateLastName ? lastName: u.LAST_NAME,
			});
}
```

which throws the following exception
```
ArgumentException: Arguments type mismatch
```

```
in System.Linq.Expressions.Expression.Condition(Expression test, Expression ifTrue, Expression ifFalse, Type type)
   in System.Linq.Expressions.ConditionalExpression.Update(Expression test, Expression ifTrue, Expression ifFalse)
   in System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)
   in System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   in Z.EntityFramework.Plus.ExpressionVisitor`1.Visit(Expression expression)
   in Z.EntityFramework.Plus.BatchUpdate.ResolveUpdateFromQueryDictValues[T](Expression`1 updateFactory)
   in Z.EntityFramework.Plus.BatchUpdate.GetInnerValues[T](IQueryable`1 query, Expression`1 updateFactory, SchemaEntityType`1 entity)
   in Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   in Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
   in Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory)
```
Can you do something about it? The old EF.Extended works fine

**Comment by JonathanMagnan** [comment] 2017-07-26 11:45
Hello @panizza ,

Thank you for reporting,

We will investigate this issue this week.

Best Regards,

Jonathan

**Comment by panizza** [comment] 2017-08-28 07:36
Is the any news? This issue prevents me switching from the old EF.Extended

**Comment by JonathanMagnan** [comment] 2017-08-28 15:51
Hello @panizza ,

I'm sorry, it seems this issue was not on our `todo` list for an unknown reason.

I will check it today and give you an update.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-08-28 23:27
Hello @panizza ,

We are not able to reproduce the issue.

Something seems to miss me to reproduce it.

Do you think you could provide a code that's not working? I will for sure try to treat this issue has priority as soon as I receive it.

```csharp
using System.Data.Entity;
using System.Linq;
using System.Windows.Forms;
using Z.EntityFramework.Plus;

namespace Z.Request.Conditional
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();

            // CLEAN
            using (var ctx = new EntityContext())
            {
                ctx.Users.RemoveRange(ctx.Users);
                ctx.SaveChanges();
            }

            // SEED
            using (var ctx = new EntityContext())
            {
                ctx.Users.Add(new User {ColumnInt = 1, STATUS = "2", FIRST_NAME = "Z_3", LAST_NAME = "Z_4"});
                ctx.Users.Add(new User {ColumnInt = 5, STATUS = "6", FIRST_NAME = "Z_7", LAST_NAME = "Z_8" });
                ctx.SaveChanges();
            }

            // TEST
            using (var ctx = new EntityContext())
            {
                bool updateStatus = true;
                bool updateFirstName = false;
                bool updateLastName = true;

                string newStatus = "9";
                string firstName = "Z_10";
                string lastName = "Z_11";

                ctx.Users
                    .Where(x => x.ColumnInt == 1)
                    .Update(u => new User
                    {
                        STATUS = updateStatus ? newStatus : u.STATUS,
                        FIRST_NAME = updateFirstName ? firstName : u.FIRST_NAME,
                        LAST_NAME = updateLastName ? lastName : u.LAST_NAME,
                    });
            }
        }

        public class EntityContext : DbContext
        {
            public EntityContext() : base("CodeFirstEntities")
            {
            }

            public DbSet<User> Users { get; set; }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                modelBuilder.Types().Configure(x => x.ToTable(GetType().DeclaringType != null ? GetType().DeclaringType.FullName.Replace(".", "_") + "_" + x.ClrType.Name : ""));

                base.OnModelCreating(modelBuilder);
            }
        }

        public class BaseUser
        {
            public string STATUS { get; set; }

            public string FIRST_NAME { get; set; }

            public string LAST_NAME { get; set; }
        }

        public class User : BaseUser
        {
            public int ID { get; set; }
            public int ColumnInt { get; set; }
        }
    }
}
```

Best Regards,

Jonathan

**Comment by panizza** [comment] 2017-08-29 13:52
Hi @JonathanMagnan,
you're right, I just tried your example and it works.
I get the "ArgumentException: Arguments type mismatch" only when I update two of my tables . I will look into that and try to get more information.

But when I update the other tables, I get the following error
```
Must declare the scalar variable "@p__linq__0".
Incorrect syntax near the keyword 'AS'.
```
SQL statament
```SQL

UPDATE A 
SET A.[STATUS] =  
    CASE WHEN (@p__linq__0 = 1) THEN N'9' ELSE B.[STATUS] END ,
A.[FIRST_NAME] =  
    CASE WHEN (@p__linq__0 = 1) THEN N'Z_10' ELSE B.[FIRST_NAME] END ,
A.[LAST_NAME] =  
    CASE WHEN (@p__linq__0 = 1) THEN N'Z_11' ELSE B.[LAST_NAME] END 
FROM [dbo].[users] AS A
INNER JOIN ( SELECT 
    [Extent1].[ID] AS [ID], 
    [Extent1].[ColumnInt] AS [ColumnInt], 
    [Extent1].[STATUS] AS [STATUS], 
    [Extent1].[FIRST_NAME] AS [FIRST_NAME], 
    [Extent1].[LAST_NAME] AS [LAST_NAME]
    FROM [dbo].[users] AS [Extent1]
    WHERE 1 = [Extent1].[ColumnInt]
           ) AS B ON A.[ID] = B.[ID]

```

My production code is slightly different. I've a class which contains the boolean variables.

Can you please try and add the following code?
```csharp 
public class UpdateFields
{
    public bool updateStatus { get; set; }
    public bool updateFirstName { get; set; }
    public bool updateLastName { get; set; }
}
```
and then change your update statement as follows
```csharp
var update = new UpdateFields() 
{
    updateStatus = true,
    updateFirstName = false,
    updateLastName = true
};

ctx.Users
	.Where(x => x.ColumnInt == 1)
	.Update(u => new User
	{
		STATUS = update.updateStatus ? newStatus : u.STATUS,
		FIRST_NAME = update.updateFirstName ? firstName : u.FIRST_NAME,
		LAST_NAME = update.updateLastName ? lastName : u.LAST_NAME,
	});
```

Thanks

**Comment by JonathanMagnan** [comment] 2017-08-29 19:34
Hello @panizza ,

Thank you, we successfully reproduced the issue and fixed it.

The fix will be available with the release that will be available this night or tomorrow morning.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-08-30 01:35
Hello @panizza ,

The v.1.6.17 has been released.

This issue should be now fixed.

Feel free to reopen this issue if you still have the problem

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2017-08-30 01:35 UTC
