### ISSUE TITLE
QueryFilter Slow Performance with .Include

### ISSUE THREAD

**Issue by jasonhjohnson** [zzzprojects/EntityFramework-Plus#276] opened 2017-11-27 15:07 UTC
Hi,

I'm using the latest stable release of the framework and have noticed really slow performance on queries with a `.Include`.

For example, this is fast:
```
await this.context.ProductCategories                                
                                .OrderBy(x => x.CategoryCode)                              
                                .ToListAsync();
```

While this is slow (around 10 seconds):
```
await this.context.ProductCategories
                                .Include(x => x.Plant)
                                .OrderBy(x => x.CategoryCode)                               
                                .ToListAsync();
```

The "ProductCategory" model inherits from: `IPlant` and `IBaseEntity` interfaces which have query filters applied as follows:
```
this.context.Filter<IPlant>(QueryFilterType.TenantForPlant, q => q.Where(x => x.Plant.TenantId == tenantId));

this.context.Filter<IBaseEntity>(QueryFilterType.SoftDelete, q => q.Where(x => !x.IsDeleted));
```

Any help is appreciated.

Thanks,
Jason

**Comment by jasonhjohnson** [comment] 2017-11-27 15:34
It seems like this could be due to the latest EF Core: https://github.com/aspnet/EntityFrameworkCore/issues/10256

Even the following query is slow:
```
this.context.ProductCategories.AsNoFilter()
                                .Include(x => x.Plant)
                                .OrderBy(x => x.CategoryCode)
                                .Where(x => x.Plant.TenantId.Equals(tenantId))
                                .ToList();
```

**Comment by JonathanMagnan** [comment] 2017-11-27 22:13
Hello @jasonhjohnson ,

Thank you for reporting and letting us know about the one on EF Core.

I do not believe there is anything we can do since we only change the `DbSet` query and nothing else but we will still look at it during the week.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-12-01 22:14
Hello @jasonhjohnson ,

After making some test, I also believe this is due to the EF Core Issue: aspnet/EntityFrameworkCore#10256

Can we close this thread since our library doesn't seem to be the cause?

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by jasonhjohnson** [comment] 2017-12-04 16:21
Thanks for checking and yes we can close.

**Closed** 2017-12-04 19:28 UTC
