### ISSUE TITLE
QueryIncludeFilterParentQueryable always looking for an x

### ISSUE THREAD

**Issue by devfxplayer** [zzzprojects/EntityFramework-Plus#506] opened 2019-08-13 11:32 UTC
QueryIncludeFilterParentQueryable line 137 the object does not have an x value

**Comment by JonathanMagnan** [comment] 2019-08-13 12:20
Hello @devfxplayer ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment] 2019-08-26 00:30
Hello @devfxplayer ,

Unfortunately, we will need to close this issue.

As a free product, we require a runnable project sample. We don't have time to re-create everyone issue ;(

**Closed by JonathanMagnan** 2019-08-26 00:30 UTC
