### ISSUE TITLE
Update batch with backreference

### ISSUE THREAD

**Issue by pelhu** [zzzprojects/EntityFramework-Plus#107] opened 2017-01-02 12:08 UTC
Hello,
I have problems when updating my entity.

I put the details above:

C#: 
```c#
db.Customers.Where(c => c.Id == customer.Id).Update(c => new Customer { Reputation_Current_Count = c.Reputation_Current_Count + 1 });
```

Generated SQL : 
```sql
exec sp_executesql N'
UPDATE A 
SET A.[Reputation_Current_Count] =  [c].[Reputation_Current_Count] + 1
FROM [Customers] AS A
INNER JOIN ( SELECT [c].[Id], [c].[Authkey], [c].[Name], [c].[Phishing_Day_Limit], [c].[Reputation_Current_Count], [c].[Reputation_Current_Date], [c].[Reputation_Day_Limit]
FROM [Customers] AS [c]
WHERE [c].[Id] = @__customer_Id_0
           ) AS B ON A.[Id] = B.[Id]
',N'@__customer_Id_0 int',@__customer_Id_0=2
```

SQL Error :  
```
The multi-part identifier "c.Reputation_Current_Count" could not be bound.
```

**Comment by zzzprojects** [comment] 2017-01-02 12:51
Hello @pelhu ,

Thank you for reporting this error.

We will look at this issue later today. I hope to get it fixed by tomorrow.

Best Regards,

Jonathan

**Comment by pelhu** [comment] 2017-01-02 13:16
:thumbsup:

**Comment by JonathanMagnan** [comment] 2017-01-03 01:41
Hello @pelhu ,

Unfortunately, I couldn't reproduce this issue. It seems to work as intended in my environment.

Can you give me the following information:
- Entity Framework Version
- Database Provider (SQL Server, MySQL, etc.)

Best Regards,

Jonathan

**Comment by pelhu** [comment] 2017-01-03 05:51
Hello @JonathanMagnan ,
Of course,
```SQLServer```

Project.json
```{
  "dependencies": {
    "BundlerMinifier.Core": "2.2.306",
    "Crypttech.Helpers": "1.0.40",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Mvc.WebApiCompatShim": "1.1.0",
    "Microsoft.AspNetCore.Razor.Tools": {
        "version": "1.0.0-preview2-final",
        "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
        "version": "1.0.0-preview2-final",
        "type": "build"
    },
    "System.IO": "4.3.0",
    "ThreatIntelligenceCore": "1.0.0-*",
    "Z.EntityFramework.Plus.BatchDelete.EFCore": "1.4.13",
    "Z.EntityFramework.Plus.BatchUpdate.EFCore": "1.4.13"  },

    "tools": {
        "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
        "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
        "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
        "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
        "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
            "version": "1.0.0-preview2-final",
            "imports": [
                "portable-net45+win8"
            ]
        }
    },

  "frameworks": {
    "net462": { }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}```

**Comment by JonathanMagnan** [comment] 2017-01-03 17:57
Hello @pelhu ,

We successfully reproduced the issue. I probably tested your example twice in EF6 instead of using EF Core the second time.

The v1.4.20 is now available:
https://www.nuget.org/packages/Z.EntityFramework.Plus.BatchUpdate.EFCore/

Let us know if the issue is fixed

Best Regards,

Jonathan

**Comment by pelhu** [comment] 2017-01-04 05:47
Hi @JonathanMagnan ,
It work like a charm :)

Thank you

Best Regards,

Khamzat

**Comment by pelhu** [comment] 2017-01-04 05:48
Hi @JonathanMagnan ,
It work like a charm :)

Thank you

Best Regards,

Khamzat

**Comment by pelhu** [comment] 2017-01-09 09:35
Hello @JonathanMagnan 
I am sorry but more one problem.
I have added "count" instead of "1"

```c#
var count = ressourcesArr.Count;
db.Customers.Where(c => c.Id == customer.Id).Update(c => new Customer { Reputation_Current_Count = c.Reputation_Current_Count + count });
```
It generate
```SQL
exec sp_executesql N'
UPDATE A 
SET A.[Reputation_Current_Count] =  B.[Reputation_Current_Count] + @__count_1
FROM [Customers] AS A
INNER JOIN ( SELECT [c].[Id], [c].[Authkey], [c].[Name], [c].[Phishing_Day_Limit], [c].[Reputation_Current_Count], [c].[Reputation_Current_Date], [c].[Reputation_Day_Limit]
FROM [Customers] AS [c]
WHERE [c].[Id] = @__customer_Id_0
           ) AS B ON A.[Id] = B.[Id]
',N'@__customer_Id_0 int',@__customer_Id_0=2
```
With sql error 
```SQL
Msg 137, Level 15, State 2, Line 3
Must declare the scalar variable "@__count_1".
Msg 156, Level 15, State 1, Line 8
Incorrect syntax near the keyword 'AS'.
```
Best Regards

**Comment by JonathanMagnan** [comment] 2017-01-09 14:25
Thank you,

Yup, it looks EF Core really doesn't generate SQL like it was doing for EF5 && EF6.

We will try to check this issue later today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-01-12 01:37
Hello @pelhu ,

The v1.4,22 has been released.

Variable should now be resolved when used with a combination of property from the lambda expression.

Let us know if it's now working.

Best Regards,

Jonathan

**Comment by kexxxfeng** [comment] 2017-06-01 08:26
Hello,
I met this issue again.But I have a bit of difference that the relationship of my entities were more to more.
Their relationship like below:

 PostTag |  PostToTag | Post
 --- | --- | ---
 n | 1 | n

```c#
 var query = from tag in _dbContext.Set<Entities.PostTag>()
                        join to in _dbContext.Set<Entities.PostToTag>() on tag.Id equals to.TagId
                        where postIds.Contains(to.PostId)
                        select tag;
 await query.UpdateAsync(t => new Entities.PostTag
            {
                UseCount = t.UseCount - 1
            });
```
> The `postIds` was an argument I sent.

Then the sql was:
```sql

UPDATE A 
SET A.[UseCount] =  [tag].[UseCount] - 1
FROM [blog_Tag] AS A
INNER JOIN ( SELECT [tag].[TagID], [tag].[BlogId], [tag].[CreateTime], [tag].[TagName], [tag].[UseCount]
FROM [blog_Tag] AS [tag]
INNER JOIN [blog_Tag_Entry] AS [to] ON [tag].[TagID] = [to].[TagID]
WHERE [to].[EntryID] IN (3549)
           ) AS B ON A.[TagID] = B.[TagID]

```
The error was reported by SqlServer
```
Msg 4104, Level 16, State 1, Line 3
The multi-part identifier "tag.UseCount" could not be bound.
```
My csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.6</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Z.EntityFramework.Plus.EFCore" Version="1.6.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.2" />
  </ItemGroup>
</Project>
```

In the end, I found that the sql in the second row should be correct:
```sql
2. SET A.[UseCount] =  A.[UseCount] - 1
```
Then, it works well.

I wonder the wrong was made by EFCore or Plus?

**Comment by JonathanMagnan** [comment] 2017-06-01 12:00
Hello @kexxxfeng ,

Thank you for reporting, we will look at it for sure during the weekend.

The issue probably comes from this line `select tag;`. It looks to rename the default SQL Alias with it. We will try to find a better solution to handle SQL Alias generated by Entity Framework.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-06-10 00:35
Hello @kexxxfeng ,

The v1.6.1 has been released.

Let me know if that's now working with this situation.

Best Regards,

Jonathan

**Comment by kexxxfeng** [comment] 2017-06-10 01:26
Thx for you very much! 

It works very well.

```sql
UPDATE A 
SET A.[UseCount] = B.[UseCount] - 1
FROM [blog_Tag] AS A
INNER JOIN ( SELECT [tag].[TagID], [tag].[BlogId], [tag].[CreateTime], [tag].[TagName], [tag].[UseCount]
FROM [blog_Tag] AS [tag]
INNER JOIN [blog_Tag_Entry] AS [to] ON [tag].[TagID] = [to].[TagID]
WHERE [to].[EntryID] IN (4589) 
           ) AS B ON A.[TagID] = B.[TagID]
```

The generated sql was correct.

**Comment by JonathanMagnan** [comment] 2017-06-10 11:35
Closing Comment: Fix confirmed

**Closed by JonathanMagnan** 2017-06-10 11:35 UTC
