### ISSUE TITLE
virtual Properties support for ef core UseLazyLoadingProxies

### ISSUE THREAD

**Issue by davious** [zzzprojects/EntityFramework-Plus#389] opened 2018-07-31 01:59 UTC
UseLazyLoadingProxies is new in ef core 2.1

When I try to add a migration with `DbSet<AuditEntry> AuditEntries`, I get
Navigation property 'Properties' on entity type 'AuditEntry' is not virtual. UseLazyLoadingProxies requires all entity types to be public, unsealed, have virtual navigation properties, and have a public or protected constructor.

Would you change the `Properties` property to `virtual` to support UseLazyLoadingProxies in ef core 2.1?

**Comment by JonathanMagnan** [comment] 2018-07-31 02:14
Hello @davious ,

Do you think you could provide a "working" project example/test with this issue?

It will make easier/faster for my developer to getting started for investigating it.

_You can send it to info@zzzprojects.com if you need to keep the source private_

_We now always ask for a project since we found out that most issues are missing some essential information, have some syntax mistake or are resolved by the requestor when creating it_

_(Even if the issue seem very easy to reproduce, by getting a test project, it allow us to give a faster support and better experience for the support of all our free libraries)_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment] 2018-08-12 21:04
Hello @davious ,

This issue will be closed since we haven't heard back from you.

Feel free to reopen if you can provide further information.

Best Regards,

Jonathan

**Comment by abuassar** [comment] 2018-12-04 16:46
I encountered the same issue, and made the following demo project:
[WebApplication1.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/2644924/WebApplication1.zip)

How to reproduce:
1- open the project in VS
2- enter "Add-Migration audit" in the package manager console

Expected result:
a new migration is added with "AuditEntry" table

Actual result:
error message saying 
"Navigation property 'Properties' on entity type 'AuditEntry' is not virtual. UseLazyLoadingProxies requires all entity types to be public, unsealed, have virtual navigation properties, and have a public or protected constructor."

Suggested fix:
add 'virtual' to all navigation properties in AuditEntry and AuditEntryProperty

**Comment by JonathanMagnan** [comment] 2018-12-05 01:44
Hello @abuassar ,

Thank you for the project, we have re-open the issue and we will look at it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by abuassar** [comment] 2018-12-05 13:53
I'm looking forward to using EntityFramework-Plus auditing feature ASAP
thanks for your hard work

**Comment by JonathanMagnan** [comment] 2019-01-17 17:03
Hello @abuassar ,

I'm sorry, we forget to answer you last month.

By developer when looked at it successfully make it work when adding the keyword `virtual` but unfortunately we cannot do it due to possible since impact.

One way to do it on your side is by using a solution similar to the database approach by creating your own auditing entity and "importing it".

See the following online example: https://dotnetfiddle.net/9XjCSM

Again sorry for the late answer.

**Closed** 2019-02-12 16:17 UTC
