### ISSUE TITLE
Target .NET Standard 2.0 for EF Core 3.1

### ISSUE THREAD

**Issue by Frudy** [zzzprojects/EntityFramework-Plus#553] opened 2019-12-04 20:12 UTC
EF Core 3.1 now targets .NET Standard 2.0 as opposed to .NET Standard 2.1 for 3.0.
This makes it much easier for large projects (like ours) to transition from .NET classic to .NET Core, since both EF 6 and EF Core can now be used from .NET 4.7.2 in a transitional period.

Since our project relies heavily on the fabulous EntityFramework-Plus and EntityFramework-Extended frameworks, a target for .NET Stardard 2.0 is needed for continued usage.

**Comment by JonathanMagnan** [comment] 2019-12-05 14:50
Hello @Frudy ,

Thank you for reporting. We are currently looking at how we will handle it since we didn't expect that change ;)

I believe a new version will be released next Monday.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment] 2019-12-11 21:52
Hello @Frudy ,

The v3.0.25 has been finally released

Could you try it and confirm that everything is working fine with the .NET Standard 2.0 version?

**Comment by mabbond** [comment] 2019-12-13 06:16
Hi, I'm trying the v 3.0.29 in a NetStandard 2.0 project but when I try to execute this query
`var mov = _dataSource.MovimientoInventarioVentas.Where(m => m.DetVenta.VentaId == id).Include("Inventario.ProductoPresentacion.Producto.Descripcion").AsNoTracking().Future();`

I get a 'System.InvalidOperationException' in System.Private.CoreLib.dll
The underlying reader doesn't have as many fields as expected.

The same happens when I try this another query.
` queryFiado = _dataSource.DetCobros.Where(r => r.Cobro.Venta.ClienteId == id && r.Cobro.Venta.Anulada == false).DeferredSum(r => r.Cantidad).FutureValue<decimal?>()`;

**Comment by JonathanMagnan** [comment] 2019-12-13 14:05
Hello @mabbond ,

This error happen because you have enabled `EnableRetryOnFailure` probably.

Someone already reported it and one of my developers is already working on it.

Please, make sure to open a new issue otherwise it makes it hard for us to follow-up

**Comment by mabbond** [comment] 2019-12-13 15:25
Thanks a lot @JonathanMagnan , disabling the `EnableRetryOnFailure`did the trick, until the bug is fixed.

**Closed** 2019-12-18 14:07 UTC

**Comment by Sandeep321** [comment] 2021-02-24 06:22
Hi @JonathanMagnan Is this issue fixed?

"The underlying reader doesn't have as many fields as expected"

**Comment by JonathanMagnan** [comment] 2021-02-25 03:41
Hello @Sandeep321 ,

My developer told me that this is fixed for EF Core 5 since the 6 December 2020 and EF Core 3 since December 2019.

Did you get this error?

**Comment by Sandeep321** [comment] 2021-02-25 07:09
To be honest, I am getting this with EFCore package, not with your package "EntityFramework-Plus".
I could be of help if you could guide me on what the issue is and how this could be solved when using EF Core itself.

**Comment by JonathanMagnan** [comment] 2021-02-25 13:37
Hello @Sandeep321 ,

Report it to the right repository? https://github.com/dotnet/efcore/issues

There is nothing we can do on our side, we don't own the source of EF Core.
