### ISSUE TITLE
Can't write CLR type Z.EntityFramework.Plus.AuditEntryState with handler type Int32Handler

### ISSUE THREAD

**Issue by armitagemderivitec** [zzzprojects/EntityFramework-Plus#413] opened 2018-09-25 10:57 UTC
Hi there,

I've just upgraded to the latest Npgsql library (4.0.3) and the latest version of the Z.EntityFramework.Plus.Audit.EF6 and Z.EntityFramework.Plus.EF6 libraries versions (1.8.5 / 1.8.10) and now receive the following error:

```
System.InvalidCastException : Can't write CLR type Z.EntityFramework.Plus.AuditEntryState with handler type Int32Handler
   at lambda_method(Closure , NpgsqlTypeHandler , Object , NpgsqlLengthCache& , NpgsqlParameter )
   at Npgsql.TypeHandling.NpgsqlSimpleTypeHandler`1.ValidateObjectAndGetLength(Object value, NpgsqlLengthCache& lengthCache, NpgsqlParameter parameter)
   at Npgsql.NpgsqlParameter.ValidateAndGetLength()
   at Npgsql.NpgsqlCommand.ValidateParameters()
   at Npgsql.NpgsqlCommand.<ExecuteDbDataReader>d__100.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at .(DbCommand , BulkOperation , Int32 )
   at .( , DbCommand )
   at .Execute(List`1 actions)
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.EntityFramework.Extensions.EntityBulkOperation`1.BulkInsert()
   at .[](BulkOperation`1 this, DbContext , List`1 , Boolean , List`1 , Type , String )
   at .`1.(SchemaEntityType )
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at .[](DbContext this, BulkOperation`1 , IEnumerable`1 , List`1 )
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 bulkOperationFactory)
```

Any help would be greatly appreciated.

Many thanks 

Mike

**Comment by armitagemderivitec** [comment] 2018-09-25 11:12
Hi, 

For the time being I have downgraded Npgsql to 3.2.7 which works perfectly and I'm therefore no longer blocked, so no rush on the resolution.

Thanks 

Mike

**Comment by JonathanMagnan** [comment] 2018-09-26 03:10
Hello @armitagemderivitec ,

Thank you for reporting. We are currently investigating CLR under PostgreSQL, perhaps the upgrade to `4.0.3` might give us some hint as we have faced some breaking change starting on Npgsql `4.x`

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2018-10-08 01:07
Hello @armitagemderivitec ,

The issue was caused with `Entity Framework Extensions` and `CLR Type`

Could you try the EFE v3.16.3 that has been released today to see if the issue has been resolved?

The issue still exists with PostgreSQL v4.x due to some breaking change in their API, we are currently looking at it (The fix already exists in our EFE Core version, we just need to check about side impact).

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2018-10-14 14:14
Hello @armitagemderivitec ,

Did you have the chance to try it?

**Comment by armitagemderivitec** [comment] 2018-10-16 14:55
Hi @JonathanMagnan,

I've upgraded to v3.6.15 but the issue still remains unfortunately.

**Comment by JonathanMagnan** [comment] 2018-10-17 03:44
Hello @armitagemderivitec ,

We just tried and we cannot reproduce it.

It's possible to provide us a light project with this issue?

Best Regards,

Jonathan

**Comment by armitagemderivitec** [comment] 2018-10-17 09:13
Hi @JonathanMagnan,

The error triggers during  our SaveChanges override in the DbContext. It appears that the bulk insert of the audit entries is the culprit:
```
public override int SaveChanges()
        {
            var audit = new Audit();
            audit.PreSaveChanges(this);
            this.BulkSaveChanges();
            audit.PostSaveChanges();

            if (audit.Entries.Count > 0)
            {
                this.BulkInsert(audit.Entries);
            }
        }
```

Did you test using the Audit feature? 

If you were testing under the same circumstances I'll try and rustle something up for you.

Regards,

Mike

**Comment by JonathanMagnan** [comment] 2018-10-17 20:50
Hello @armitagemderivitec ,

Yes, we made our test with the audit.

A sample with the issue will certainly help us.

Best Regards,

Jonathan

**Comment by armitagemderivitec** [comment] 2018-11-23 16:16
Hey Jonathan,

Really sorry, I'm totally snowed. Will get round to it after my project finishes in a couple of weeks.

Cheers

**Comment by SonicGD** [comment] 2018-12-03 07:46
I think it is related to this npgsql issue - https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/489. 

I was able to reproduce when `where` part of the query have condition on enum field and condition value comes from a variable.

Demo - https://github.com/SonicGD/ZZZIssue413Demo. To run it you need to fix connection string values in DbContext class.

**Comment by JonathanMagnan** [comment] 2018-12-07 15:36
Hello @armitagemderivitec , @SonicGD ,

The v1.8.18 has been released.

Thank again for your project @SonicGD , we easily reproduced the issue with it.

Let me know if everything works as expected.

Best Regards,

Jonathan

**Comment by SonicGD** [comment] 2018-12-07 15:40
Yeah, it's fixed now. Thanks!

**Closed** 2018-12-07 16:16 UTC
