### ISSUE TITLE
Parameter for filter not being supplied

### ISSUE THREAD

**Issue by ljfolino** [zzzprojects/EntityFramework-Plus#54] opened 2016-09-28 15:03 UTC
When I execute a LINQ query using a filter on the context I recieve and error of:

The parameterized query '(@p__linq__0 int)SELECT 
    [Extent1].[OrderID] AS [OrderID], ' expects the parameter '@p__linq__0', which was not supplied.

The filter looks like this:
`_context.Filter<Order>(q => q.Where(i => i.Shipper.CompanyId == userData.ShipperId));`

The query has this at the end `[Extent1].[ShipperID] = @p__linq__0)`

If I change the `userData.ShipperId` to be a literal of 1 the query works.  It appears the that value is not being passed in for some reason.  I have global filters enabled to handle soft deletes but I have disabled them and still have this issue.

**Comment by zzzprojects** [comment] 2016-09-28 16:40
Thank you @ljfolino ,

We successfully reproduce this issue.

The issue starting to appear in the Query Filter revamp to use Interceptor for supporting Lazy Loading, Include, etc.. starting from version 1.4.x

**Comment by ljfolino** [comment] 2016-09-28 17:08
This did work at one point.  Any idea what could have introduced this issue?  I had the same code running and tested with the 1.4.0 version.

**Comment by zzzprojects** [comment] 2016-10-04 18:28
Hello @ljfolino ,

Just to give you an update. We now understand why this is happening. Unfortunately, we tried this weekend, but we didn't successfully found how to fix it. We will try for sure again to find a solution before next week, but we cannot promise anything since this kind of issue is sometimes very hard to fix.

**Comment by ljfolino** [comment] 2016-10-04 20:30
I reverted to the 3.x version and am using that for the time being.

**Comment by zzzprojects** [comment] 2016-10-15 19:39
Hello @ljfolino , 

We finally found some time to work on this issue and we are getting closer to a resolution.

We have found a good workaround which fixes this issue by using constant value instead of the parameter (exactly like if you was using a literal in your filter expression).  There is some work to do to make sure this fix is our best options available, but we are pretty sure a fix will be available on Monday.

I will let you know updated.

**Comment by zzzprojects** [comment] 2016-10-16 19:33
Hello @ljfolino ,

The v1.4.8 has been released.

Can you try again with the new version and let me know if this issue is fixed?

Best Regards,

Jonathan

**Comment by ljfolino** [comment] 2016-10-18 12:47
Sorry I will not be able to test this any time soon.  I did not want to not respond though.

**Comment by zzzprojects** [comment] 2016-11-08 22:59
Hello @ljfolino ,

To reduce the number of thread in the Issue Tracker, we will close this issue since we believe we have fixed it in v1.4.8.

If you still get the issue, just re-open it when you will have the time to test it.

Best Regards,

Jonathan

**Closed by zzzprojects** 2016-11-08 22:59 UTC

**Comment by sessionliang** [comment] 2016-11-12 12:01
I think that this error from Linq, userData.ShipperId should be a const value, look like this:
var shipperId = userData.ShipperId;
....... //next code

**Comment by zzzprojects** [comment] 2016-11-12 15:38
Hello @sessionliang ,

This error was our fault not handling variable correctly. It should have been fixed in v1.4.8
