### ISSUE TITLE
Support for Contains method in Where

### ISSUE THREAD

**Issue by lestera** [zzzprojects/EntityFramework-Plus#180] opened 2017-07-05 11:25 UTC
Hi,
Doing the following throws an exception:
```
IEnumerable<string> ids = new[] { "id1", "id2" };
ctx.Users.Where(x => ids.Contains(x.Id)).Update(x => new User { ... });
```
Is `Contains` not supported in `Where`? If not, how hard would it be to add support for this?
Thanks

Exception details:
```
System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Id'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory)
```

The following is the statement that it tries to execute. There isn't an `IN` operator here, so I'm guessing this isn't just a bug in the statement that can be fixed with a few lines of code.
```
UPDATE A 
SET A.[Session] = @zzz_BatchUpdate_0
FROM [dbo].[Users] AS A
INNER JOIN ( SELECT 
    CAST(NULL AS varchar(1)) AS [C1], 
    CAST(NULL AS int) AS [C2], 
    CAST(NULL AS int) AS [C3], 
    CAST(NULL AS varchar(1)) AS [C4], 
    CAST(NULL AS datetime2) AS [C5], 
    CAST(NULL AS varchar(1)) AS [C6]
    FROM  ( SELECT 1 AS X ) AS [SingleRowTable1]
    WHERE 1 = 0
           ) AS B ON A.[Id] = B.[Id]
```

**Comment by JonathanMagnan** [comment] 2017-07-05 11:36
Hello @lestera ,

We just made a test, and it works as expected.

I believe the issue is maybe in the Update part?

Could you use SQL Profiler and provide us the SQL executed? That will help us to try to reproduce this issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-07-05 11:59
Your SQL statement INNER JOIN is weird ;) The first time I see something like this.

Which version of Entity Framework are you using? Perhaps, we don't test with the same version.

Here is the one generated on my side

```sql
UPDATE  A
SET     A.[ColumnInt] = @zzz_BatchUpdate_0
FROM    [dbo].[Z_EntityFramework_Plus_Lab_Form_Request_BatchUpdate_EntitySimple]
        AS A
        INNER JOIN ( SELECT [Extent1].[ID] AS [ID] ,
                            [Extent1].[ColumnInt] AS [ColumnInt]
                     FROM   [dbo].[Z_EntityFramework_Plus_Lab_Form_Request_BatchUpdate_EntitySimple]
                            AS [Extent1]
                     WHERE  [Extent1].[ColumnInt] IN ( 1, 2 )
                   ) AS B ON A.[ID] = B.[ID]
```

**Comment by lestera** [comment] 2017-07-05 12:02
Entity Framework 6.
I'll update once I've narrowed down the issue.

**Comment by lestera** [comment] 2017-07-05 12:08
OK, I found the issue - this only happens when the `ids` collection is empty.
So to reproduce:

```
IEnumerable<string> ids = new string[] {  };
ctx.Users.Where(x => ids.Contains(x.Id)).Update(x => new User { ... });
```

**Comment by JonathanMagnan** [comment] 2017-07-05 12:26
Thank you @lestera ,

We successfully reproduced it.

We will try to solve it tomorrow. We will make some test to know if we should or not use the [SingleRowTable1] act like a "WHERE(x  => False)" clause (So nothing it executed).

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-07-10 18:02
Hello @lestera ,

The v1.6.5 has been released.

The issue has been fixed for Batch Delete && Batch Update.

Let me know if that's now working.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-07-23 18:17
Closing Comment: Fix Release

**Closed by JonathanMagnan** 2017-07-23 18:17 UTC
