### ISSUE TITLE
when use method 'Delete'  throwe Object reference not set to an instance of an object 

### ISSUE THREAD

**Issue by mushramb0** [zzzprojects/EntityFramework-Plus#351] opened 2018-04-27 03:34 UTC
I use 'MySql.Data.EntityFrameworkCore 8.0.11',when i debug,i found dll 'MySql.Data.EntityFrameworkCore' do not have type 'MySQL.Data.EntityFrameworkCore.MySQLMetadataExtensions'.
the exception is 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Z.EntityFramework.Plus.BatchDelete.CreateCommand(IQueryable query, IEntityType entity) in C:\Users\smartdo\source\repos\EntityFramework-Plus\src\shared\Z.EF.Plus.BatchDelete.Shared\BatchDelete.cs:line 565
   at Z.EntityFramework.Plus.BatchDelete.Execute[T](IQueryable`1 query) in C:\Users\smartdo\source\repos\EntityFramework-Plus\src\shared\Z.EF.Plus.BatchDelete.Shared\BatchDelete.cs:line 322
   at Z.EntityFramework.Plus.BatchDeleteExtensions.Delete[T](IQueryable`1 query, Action`1 batchDeleteBuilder) in C:\Users\smartdo\source\repos\EntityFramework-Plus\src\shared\Z.EF.Plus.BatchDelete.Shared\Extensions\Delete.cs:line 49
   at Z.EntityFramework.Plus.BatchDeleteExtensions.Delete[T](IQueryable`1 query) in C:\Users\smartdo\source\repos\EntityFramework-Plus\src\shared\Z.EF.Plus.BatchDelete.Shared\Extensions\Delete.cs:line 24
   at Scc.AmazonSellerCentral.Core.Program.Main(String[] args) in C:\Users\smartdo\Desktop\Repos\SCC.Spider\Scc.AmazonSellerCentral\Scc.AmazonSellerCentral.App\Program.cs:line 42

**Comment by JonathanMagnan** [comment] 2018-04-27 04:34
Hello @mushramb0 ,

Thank you for reporting, we will look at it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2018-05-07 13:14
Hello @mushramb0 ,

Unfortunately, it looks that some major change has been made starting from version 8.x and we didn't find how to support it.

Here are some alternative solution

## Use version 6.x
Our library already works well with this version.

## Use pomelo
Our library also supports this provider.

## Use our consultations services
If your company is ready to pay for some research and development, we may investigate this issue more and find a solution. We offer reasonable fixed price and only get paid on successful request.
You can contact us about it here: info@zzzprojects.com

Best Regards,

Jonathan

**Comment by livershi** [comment] 2018-05-10 03:33
Z.EntityFramework.Plus.EFCore 1.7.19
i use MySql.Data.EntityFrameworkCore 6.0,but i got error by Delete and Update.
 System.NullReferenceException: Object reference not set to an instance of an object.
   at Z.EntityFramework.Plus.BatchDelete.CreateCommand(IQueryable query, IEntityType entity)
   at Z.EntityFramework.Plus.BatchDelete.Execute[T](IQueryable`1 query)

**Comment by livershi** [comment] 2018-05-10 03:34
this.efContext.News.Where(p => p.Id < 10)
                .Delete();

**Comment by JonathanMagnan** [comment] 2018-05-10 13:13
Hello @livershi ,

Do you think you could provide us a test project with this issue?

It will make easier/faster for my developer to getting started for investigating it.

_We now always ask for a project since we found out that most issues are missing some essential information or are resolved by the requestor when creating it_

_(Even if the issue seem very easy to reproduce, by getting a test project, it allow us to give a faster support and better experience for the support of all our free libraries)_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment] 2018-05-22 20:40
Hello @livershi ,

This issue will be closed since we haven't heard back from you.

Feel free to reopen it if you can provide the information we asked.

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2018-05-22 20:40 UTC
