### ISSUE TITLE
IncludeOptimized With multiple levels

### ISSUE THREAD

**Issue by maleet** [zzzprojects/EntityFramework-Plus#91] opened 2016-12-02 08:37 UTC
You already have my .edmx file from another issue. 

Problem with query:
```
var productionOrders = Entities.ProductionOrders
.IncludeOptimized(order => order.ItemDetailHeader.ItemDetailLines.Select(x => x.Property))
.IncludeOptimized(order => order.PegsByLeftOrderId)
.IncludeOptimized(order => order.PegsByRightOrderId)
.IncludeOptimized(order => order.Operations.Select(operation => operation.Children.Select(task => task.InputInstructions.Select(instruction => instruction.Pegs))))
.IncludeOptimized(order => order.Operations.Select(operation => operation.Children.Select(task => task.OutputInstructions.Select(instruction => instruction.Pegs))))
.IncludeOptimized(order => order.Operations.Select(operation => operation.Children.Select(task => task.UseInstructions)))
.IncludeOptimized(order => order.MasterOperations.Select(operation => operation.MasterInputInstructions))
.IncludeOptimized(order => order.MasterOperations.Select(operation => operation.MasterOutputInstructions))
.IncludeOptimized(order => order.MasterOperations.Select(operation => operation.MasterUseInstructions))
.IncludeOptimized(order => order.MasterOperations.Select(operation => operation.Process))
.ToList()
```

With EF Include productionOrders have total of 823 ItemDetailHeaders, with IncludeOptimized there is 0 of them.

**Comment by zzzprojects** [comment] 2016-12-02 15:04
Hello Mart,

By default, IncludeOptimized only includes the last level. It doesn't Include automatically multiple level yet.

There is two way to fix this issue

**AllowIncludeSubPath**
Using the AllowIncludeSubPath  options.
```csharp
QueryIncludeOptimizerManager.AllowIncludeSubPath = true;
```

**Include level**
Including yourself every level.

```csharp
var productionOrders = Entities.ProductionOrders
.IncludeOptimized(order => order.ItemDetailHeader)
.IncludeOptimized(order => order.ItemDetailHeader.ItemDetailLines)
.IncludeOptimized(order => order.ItemDetailHeader.ItemDetailLines.Select(x => x.Property))
.IncludeOptimized(order => order.PegsByLeftOrderId)
.IncludeOptimized(order => order.PegsByRightOrderId)
.IncludeOptimized(order => order.Operations)
.IncludeOptimized(order => order.Operations.Select(operation => operation.Children)
.IncludeOptimized(order => order.Operations.Select(operation => operation.Children.Select(task => task.InputInstructions)
.IncludeOptimized(order => order.Operations.Select(operation => operation.Children.Select(task => task.InputInstructions.Select(instruction => instruction.Pegs))))
.IncludeOptimized(order => order.Operations.Select(operation => operation.Children.Select(task => task.OutputInstructions)
.IncludeOptimized(order => order.Operations.Select(operation => operation.Children.Select(task => task.OutputInstructions.Select(instruction => instruction.Pegs))))
.IncludeOptimized(order => order.Operations.Select(operation => operation.Children.Select(task => task.UseInstructions)))
.IncludeOptimized(order => order.MasterOperations
.IncludeOptimized(order => order.MasterOperations.Select(operation => operation.MasterInputInstructions))
.IncludeOptimized(order => order.MasterOperations.Select(operation => operation.MasterOutputInstructions))
.IncludeOptimized(order => order.MasterOperations.Select(operation => operation.MasterUseInstructions))
.IncludeOptimized(order => order.MasterOperations.Select(operation => operation.Process))
.ToList()
```

**Note**
For a big query like this one, IncludeOptimized can be slower than include itself. When multiple level is involved, Entity Framework doesn't always create an optimized query for our features.

Best Regards,

Jonathan

**Comment by maleet** [comment] 2016-12-03 12:01
Thanks, I thought there must be a way for this. 
I try to split my query to separate queries as for now it takes couple of seconds. Both ones, include and also includeOptimized

**Comment by zzzprojects** [comment] 2016-12-04 18:01
Another way which may improve your performance is splitting the queries in a smaller part.

Entity Framework is very bad to handle such big queries. It takes a lot of times to generate the plan and even more to execute it!

By splitting it and using EF+ Future features, you still make only one database round-trip but every query is lighter (this is what our library do under the hood).

**Example**
```csharp
var productionOrders = Entities.ProductionOrders
.Include(order => order.ItemDetailHeader.ItemDetailLines.Select(x => x.Property))
.Include(order => order.PegsByLeftOrderId)
.Include(order => order.PegsByRightOrderId)
.Future();

productionOrders = Entities.ProductionOrders
.Include(order => order.Operations.Select(operation => operation.Children.Select(task => task.InputInstructions.Select(instruction => instruction.Pegs))))
.Include(order => order.Operations.Select(operation => operation.Children.Select(task => task.OutputInstructions.Select(instruction => instruction.Pegs))))
.Include(order => order.Operations.Select(operation => operation.Children.Select(task => task.UseInstructions)))
.Future();

productionOrders = Entities.ProductionOrders
.Include(order => order.MasterOperations.Select(operation => operation.MasterInputInstructions))
.Include(order => order.MasterOperations.Select(operation => operation.MasterOutputInstructions))
.Include(order => order.MasterOperations.Select(operation => operation.MasterUseInstructions))
.Include(order => order.MasterOperations.Select(operation => operation.Process))
.Future()
.ToList();
```

**Comment by bgradin** [comment] 2017-11-30 22:29
Has anyone been able to solve this issue with the above suggestions? I have the following simple use case:

```
var result = Foo
    .Where(fooPredicate)
    .IncludeOptimized(x => x.Bar.AsQueryable().Where(barPredicate))
    .IncludeOptimized(x => x.Bar.Select(y => y.Qux))
    .IncludeOptimized(x => x.Baz.AsQueryable().Where(bazPredicate));
```

When I add `QueryIncludeOptimizedManager.AllowIncludeSubPath = true;`, nothing changes, except `barPredicate` isn't applied correctly`, and when I rewrite the statement like 

```
var result = Foo
    .Where(fooPredicate)
    .IncludeOptimized(x => x.Bar)
    .IncludeOptimized(x => x.Bar.Select(y => y.Qux));
```

`Qux` is still not included on `Bar`

**Comment by JonathanMagnan** [comment] 2017-11-30 22:53
Hello @bgradin ,

It's possible that AsNoTracking is used?

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by bgradin** [comment] 2017-11-30 22:55
No, AFAICT I'm not using `AsNoTracking` anywhere in my code.

**Comment by JonathanMagnan** [comment] 2017-11-30 22:59
I will try to check it during the weekend.

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment] 2017-12-04 22:29
Hello @bgradin ,

There is a few thing that I'm not sure to understand.

Why are you using `AsQueryable`? There is no point to use this method unless I'm wrong?

## Error
Here is one error in your query, it's not obvious the slight difference:

```csharp
.IncludeOptimized(x => x.Bar.AsQueryable().Where(barPredicate))
.IncludeOptimized(x => x.Bar.Select(y => y.Qux))
```

When using `IncludeSubPath` it's translate as:

- Get all bar with predicates
- Get all bar
- Get all Qux for all bar

In short, the predicate is not applied because of the second `IncludeOptimized`.

You should re-write the query like this
```csharp
.IncludeOptimized(x => x.Bar.Where(barPredicate))
.IncludeOptimized(x => x.Bar.Where(barPredicate).Select(y => y.Qux))
```

## Code
Here is the code we used, perhaps you could help us to reproduce this issue if you still have it:

```csharp
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Windows.Forms;

namespace Z.EntityFramework.Plus.Lab
{
    public partial class Form_Request_IncludeOptimized_FooBar : Form
    {
        public Form_Request_IncludeOptimized_FooBar()
        {
            InitializeComponent();

            // CLEAN
            using (var ctx = new EntityContext())
            {
                ctx.Foos.RemoveRange(ctx.Foos);
                ctx.Bars.RemoveRange(ctx.Bars);
                ctx.Qux.RemoveRange(ctx.Qux);

                ctx.SaveChanges();
            }

            // SEED
            using (var ctx = new EntityContext())
            {
                for (var i = 0; i < 5; i++)
                {
                    var foo = ctx.Foos.Add(new Foo {ColumnInt = i, Bar = new List<Bar>()});

                    for (var j = 0; j < 4; j++)
                    {
                        var bar = new Bar {ColumnInt = j, Qux = new List<Qu>()};
                        foo.Bar.Add(bar);

                        for (var k = 0; k < 3; k++)
                        {
                            bar.Qux.Add(new Qu {ColumnInt = k});
                        }
                    }
                }

                ctx.SaveChanges();
            }

            // TEST
            using (var ctx = new EntityContext())
            {
                QueryIncludeOptimizedManager.AllowIncludeSubPath = true;

                var result = ctx.Foos
                    .Where(x => x.ColumnInt > 2)
                    .IncludeOptimized(x => x.Bar)
                    .IncludeOptimized(x => x.Bar.Select(y => y.Qux))
                    .ToList();
            }
        }

        public class EntityContext : DbContext
        {
            public EntityContext() : base("CodeFirstEntities")
            {
            }

            public DbSet<Foo> Foos { get; set; }

            public DbSet<Bar> Bars { get; set; }

            public DbSet<Qu> Qux { get; set; }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                modelBuilder.Types().Configure(x => x.ToTable(GetType().DeclaringType != null ? GetType().DeclaringType.FullName.Replace(".", "_") + "_" + x.ClrType.Name : ""));

                base.OnModelCreating(modelBuilder);
            }
        }

        public class Foo
        {
            public int ID { get; set; }
            public int ColumnInt { get; set; }
            public List<Bar> Bar { get; set; }
        }

        public class Bar
        {
            public int ID { get; set; }
            public int ColumnInt { get; set; }

            public List<Qu> Qux { get; set; }
        }

        public class Qu
        {
            public int ID { get; set; }
            public int ColumnInt { get; set; }
        }
    }
}
``` 

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by bgradin** [comment] 2017-12-06 22:23
[test.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/1536858/test.zip) - includes:

- test.linq: a [LinqPad](https://www.linqpad.net/) script containing a modified version of the code you posted above, which more accurately models my use case
- script.sql: a database generation script for the accompanying database

Please note the comments in the `TEST` section of `main()`. There are several problems with the output I'm seeing:

**Observed result:**

1. Like the first comment says, if you erase the following five lines, which declare `goodResults` and `Dump()` it, the output from `badResults` and `badResults2` changes. If the first five lines are present, `badResults[0..n].Qux` and `badResults2[0..n].Qux` have 3 items in the collection. If the first five lines are *not* present, `badResults[0..n].Qux` and `badResults2[0..n].Qux` have no items in the collection.
2. When `badResults[0..n].Qux` and `badResults2[0..n].Qux` are present, they are not filtered. As you can see, given the predicate on line 74, `Qux` should be filtered to exclude instances with `ColumnInt == 0`
3. `badResults2[0..n].Bar[0..n].Qux` always has 0 items, although every instance of `Bar` has all three `Qux` instances related to it during the seeding. This is the grandchild collection that I'm trying to include and filter.

I see similar problems if I try using `IncludeFilter` instead of `IncludeOptimized`.

**Expected result:**
`badResults` and `badResults2` shouldn't be affected by other, unrelated queries. Rather, `IncludeOptimized` should always include models specified by the predicate passed into the method. Furthermore, filtering of the included models should be possible. As you can see, I've set `QueryIncludeOptimizedManager.AllowIncludeSubPath = true;`. I've also tried including each path in the query - although this step isn't in the LinqPad script. These two approaches should ensure that child collections and grandchild collections are added and filtered as desired.

**Conclusions**
One of the following must be true:

1. There is a bug in your framework
2. I am using your framework incorrectly
3. There is a bug in Entity Framework
4. I am using Entity Framework incorrectly

Being less familiar with Entity Framework and Entity Framework Plus, I am not able to discern which case(s) is/are true. Please advise, and do let me know if you have any questions about anything I've said.

Thanks!

**Comment by JonathanMagnan** [comment] 2017-12-11 19:40
Hello @bgradin ,

We looked at your scenario.

It seems you use some Many to Many relations but unfortunately, it's not yet supported for `IncludeFilter` and `IncludeOptimized`. It's currently one of the few limitations of this feature.

Perhaps the LinqPad was working since you used a different script as you specified?

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment] 2018-01-09 20:49
Hello @bgradin ,

I will close this issue since I believe there is no more activities to do on it.

Feel free to reopen it if you believe it should not have been closed.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Closed by JonathanMagnan** 2018-01-09 20:49 UTC

**Comment by bgradin** [comment] 2018-01-11 23:50
We can leave it closed, but would you mind summarizing the major roadblocks keeping many-to-many relationships from being supported?

**Comment by JonathanMagnan** [comment] 2018-01-12 16:17
Hello @bgradin ,

Our library only uses some `Entity Framework` logic such as projection with anonymous types when using `IncludeOptimized`.

However, `Many to Many` unlike other associations are not automatically bound. There is surely something we can do here but unfortunately, it takes day and day of investigation that we currently don't have.

We already have tried and for sure will try again in the future.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by bgradin** [comment] 2018-01-12 20:02
If it's a matter of a lack of time, I'd be happy to help look into it and potentially create a PR. I went ahead and forked and cloned the repository, but it looks like the tests aren't passing, due to a failed connection to the test database server. Is it possible for me to access this from my machine, or is there a schema generation script available so I can create a test database on my machine?

**Comment by JonathanMagnan** [comment] 2018-01-12 20:48
Hello @bgradin ,

You will need to change the connection string, all tables will be automatically created.

Skip test that currently fails.

Probably next week, we will commit a new version of the test with all failed test solved. One of my employees already working on this task this week. I just need to review and commit all change which should be done very soon.

Best Regards,

Jonathan
