### ISSUE TITLE
Use SetDynamic execute WhereDynamic 

### ISSUE THREAD

**Issue by XiaoBaiXJ** [zzzprojects/EntityFramework-Plus#796] opened 2024-04-10 07:10 UTC
query = query.WhereDynamic(x => $"x.{filter.PropertyName} == y)", new { y = filter.Val })

Error reporting
 An item with the same key has already been added. Key: x

**Comment by XiaoBaiXJ** [comment] 2024-04-10 07:35
![image](https://github.com/zzzprojects/EntityFramework-Plus/assets/44961186/36e24f07-c44c-442f-bd59-84926103bff9)

**Comment by JonathanMagnan** [comment] 2024-04-10 14:07
Hello @XiaoBaiXJ ,

Thank you for reporting. We will look into it.

Best Regards,

Jon

**Comment by XiaoBaiXJ** [comment] 2024-04-11 00:49
![image](https://github.com/zzzprojects/EntityFramework-Plus/assets/44961186/7a188386-73a1-4efd-a90f-7ed20248c2d1)

**Comment by XiaoBaiXJ** [comment] 2024-04-11 00:51
Using date type for querying will result in an error message

**Comment by JonathanMagnan** [comment] 2024-04-11 14:10
Hello @XiaoBaiXJ ,

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue. You can send it in private here: info@zzzprojects.com

My developer told me he tried to reproduce your issue but failed. For him, everything work so we are surely missing something to be able to reproduce the same error as you.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment] 2024-04-29 12:48
Hello @XiaoBaiXJ,

Unfortunately, since we didn't hear from you I will close this issue. 

As previously mentioned, we need a runnable project to be able to assist you. 

We will reopen the issue if a project is received. 

Feel free to contact us for questions, issues, or feedback.

Best Regards,

Jon

**Closed by JonathanMagnan** 2024-04-29 12:48 UTC
