### ISSUE TITLE
Batch Update fails for enum column

### ISSUE THREAD

**Issue by meijinyi** [zzzprojects/EntityFramework-Plus#353] opened 2018-05-04 02:49 UTC
this is my code

`public class BloggingContext : DbContext
    {
        public DbSet<Location> Locations { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseNpgsql(@"balbal");
        }
    }

     
    public class Location
    {
        [Key]
        public string ID
        { get; set; }

        public bool IsActive { get; set; } = true;

       
        public string ParentID
        {
            get;
            set;
        }

        
        public LocationLevel Level

        {
            get;
            set;
        }

         
        public string Name
        {
            get;
            set;
        }
    }

    public enum LocationLevel
    {
        Province = 1,
        City,
        Area,
        Section
    }`

` using (var db = new BloggingContext())
            {
                var q = db.Locations.Where(t => t.ID == "").Update(t => new Location { Level = LocationLevel.Area });               

                Console.WriteLine();
               
            }`

then  it runs it errors with the following:

**The CLR enum type Location must be registered with Npgsql before usage, please refer to the documentation.**

**Comment by JonathanMagnan** [comment] 2018-05-04 14:49
Hello @meijinyi ,

Do you think you could provide us a test project with this issue? Including step to support CLR enum type in PostgreSQL (or the link)

It will make easier/faster for my developer to getting started for investigating it.

_We now always ask for a project since we found out that most issues are missing some essential information or are resolved by the requestor when creating it_

_(Even if the issue seem very easy to reproduce, by getting a test project, it allow us to give a faster support and better experience for the support of all our free libraries)_

Best Regards,

Jonathan
![image](https://user-images.githubusercontent.com/23240780/39634395-b432f41c-4f88-11e8-9b10-9d15269ce819.png)

**Comment by meijinyi** [comment] 2018-05-07 01:30
@JonathanMagnan  i create a very very very simle demo  https://github.com/meijinyi/simpledemo
 and  i did not create any enum type in PostgreSQL tks.

**Comment by JonathanMagnan** [comment] 2018-05-08 23:55
Hello @meijinyi ,

Thank for the project, this task has been assigned to a developer

Best Regards,

Jonathan

**Comment by Zzzaru** [comment] 2018-06-06 19:17
It's amazingly that such a simple mistake must be corrected for so long

**Comment by bambos-xiouros** [comment] 2018-09-24 20:19
I'm having the same issue. Here's some more info.

If you map the enums to PostGres...

1 - In the DbContextConstructor map the types
`
var translator = NpgsqlConnection.GlobalTypeMapper.DefaultNameTranslator;
                NpgsqlConnection.GlobalTypeMapper.MapEnum<MyEnum>(translator.TranslateTypeName(nameof(MyEnum)));
`
2 - In OnModelCreating map the enum values
`
var translator = NpgsqlConnection.GlobalTypeMapper.DefaultNameTranslator;
                modelBuilder.ForNpgsqlHasEnum(translator.TranslateTypeName(nameof(MyEnum)), Enum.GetNames(typeof(MyEnum)).Select(_ => translator.TranslateMemberName(_)).ToArray());
`
3  - Then when you try BulkInsert
`
await context.BulkInsert(myEntities, options => options.IncludeGraph = true).ConfigureAwait(false);
`
You get an exception:
`
{System.Exception: An error occured while retrieving the InformationSchemaTable information. See the inner exception for details. ---> System.Exception: Oops! Unsupported types : USER-DEFINED
   at .( , String[] )
   at .(Boolean , String[] )
   at Z.BulkOperations.BulkOperation.()
   --- End of inner exception stack trace ---
   at Z.BulkOperations.BulkOperation.()
   at Z.BulkOperations.BulkOperation.()
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, Action`1 )
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at DbContextExtensions.BulkInsertAsync[T](DbContext this, IEnumerable`1 entities, Action`1 options, CancellationToken cancellationToken)
`

**Comment by JonathanMagnan** [comment] 2018-09-25 02:19
Hello @bambos-xiouros ,

I believe that issue has been fixed in the last version (v1.8.10)

Your case is similar but very different at the same time.

For the `BatchUpdate`,  the DbType is provided by Entity Framework and our code was missing the setter for the `NpgsqlDbType` value which is now specified.

In the case of `BulkInsert`, we are currently trying to find how to map correctly this column since this time, our library needs to find the right type. However, by posting your issue here, you just give us some idea to maybe find out what we have missed.

**Comment by bambos-xiouros** [comment] 2018-09-25 02:42
Thanks. Is there an issue I can follow for this? Nicer to have the enums if
I can.

**Comment by grehovm** [comment] 2018-11-22 07:57
I ported app to .net core and faced this problem. In ef5/6 version we have [this](https://github.com/zzzprojects/EntityFramework-Plus/blob/a91bfe38c442784e7a40a09b49f927578a551aa8/src/shared/Z.EF.Plus.BatchUpdate.Shared/BatchUpdate.cs#L602), but in ef core [we don't have it](https://github.com/zzzprojects/EntityFramework-Plus/blob/a91bfe38c442784e7a40a09b49f927578a551aa8/src/shared/Z.EF.Plus.BatchUpdate.Shared/BatchUpdate.cs#L944).

I write workaround:
```csharp
private static Action<BatchUpdate> GetBatchUpdateAction<T>()
{
    return update => update.Executing = command =>
    {
        foreach (DbParameter parameter in command.Parameters)
            if (parameter.DbType == DbType.Object && parameter.Value.GetType() == typeof(T))
            {
                var underlyingType = Enum.GetUnderlyingType(typeof(T));
                parameter.Value = Convert.ChangeType(parameter.Value, underlyingType);
            }
    };
}
```
Usage:
```csharp
await _db.Assignments.Where(x => inactivatedEmployees.Contains(x.EmployeeId) && x.Task.Deliverable.SOWId == item.Id)
    .UpdateAsync(x => new AssignmentDbModel { Status = AssignmentStatus.Disabled }, GetBatchUpdateAction<AssignmentStatus>());
```
I hope we get fix soon.

**Comment by JonathanMagnan** [comment] 2018-11-22 17:18
Hello @grehovm ,

Thank you for reporting, we will look at it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment] 2018-11-30 21:57
Hello @grehovm ,

The v1.8.17 has been released.

Let me know if that's fixed on your side.

Best Regards,

Jonathan

**Comment by grehovm** [comment] 2018-12-05 07:56
It's work, thank you.

**Closed** 2018-12-05 15:49 UTC
