### ISSUE TITLE
FromCacheAsync return reference type to exact object 

### ISSUE THREAD

**Issue by grinay** [zzzprojects/EntityFramework-Plus#503] opened 2019-08-07 02:42 UTC
Hello. 
I face into some bug, and i had to spend some time to understand where it comes from. 
Here is the code example which we use in our app. 
```

var buyTrades = (await _tradeRepository.Queryable().AsNoTracking()
                .Where(x => x.Currency == tradingPair.Currency && x.TradeCurrency == tradingPair.TradeCurrency)
                .Where(x => x.Status == TradeStatus.Open || x.Status == TradeStatus.PartiallyClosed)
                .Where(x => x.Type == TradeType.Sell)
                .GroupBy(x => x.Price)
                .OrderBy(x => x.Key)
                .Select(grp => new TradeBookOutput
                {
                    Price = grp.Key,
                    Type = TradeType.Sell,
                    Volume = grp.Sum(x => x.Amount)
                }).Take(limit)
                .FromCacheAsync(PredefinedCacheOptions.OneMinCache)).ToList();

                var reorderedList = buyTrades.OrderBy(x => x.Price).ToList();

                for (int i = 1; i < reorderedList.Count; i++)
                {
                    reorderedList[i].Volume += reorderedList[i - 1].Volume;
                }
```
            

On load test i've got error in line    reorderedList[i].Volume += reorderedList[i - 1].Volume; that value to large to be decimal. 
And then I notices that all value which came from FromCacheAsync are reference value, and mutable. So each call of this function change value in cache. I have cache applied along whole project and now i have to check all places where changes could happen.  I think this totally wrong behavior. It should return new object all the time when I request it from cache.

**Comment by JonathanMagnan** [comment] 2019-08-07 03:29
Hello @grinay ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by grinay** [comment] 2019-08-07 04:56
Yes please. 
https://dotnetfiddle.net/dP59rT review line from 30-35.

**Comment by JonathanMagnan** [comment] 2019-08-07 09:47
Thank you @grinay ,

I now better understand your issue.

However, it works as intended.

When you use the method `FromCache`, the first time it's cached in a MemoryCache. All subsequent call directly get it from the MemoryCache until the item get expired or you expire it yourself.

You normally use this cache with a read-only object or object you don't modify. In your case, you modify the value.

I believe what you were expected is a copy from the cache, so you could modify it as you want and still get a new copy with original value when you take it from the cache again.

Unfortunately, it doesn't work this way. So you will need to implement your own method that will make a `shallow copy` or `deep copy` of the object.

Hope that somewhat answer to your issue.

**Comment by grinay** [comment] 2019-08-07 10:36
Right. I already did it. But, I expected it to return copy of object. When we request content from db, with each request we  get new created object which was mapped from db records. When we add cache layer on top of it, I expect to have the same behavior.

**Comment by JonathanMagnan** [comment] 2019-08-11 12:56
Understood,  we might eventually add an option to make it works as you intend with the caching.

On my side, I expect to be the same object since the cache is common.

I will close this request but I added in our internal wishlist this request.

Have a great weekend,

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2019-08-11 12:56 UTC
