### ISSUE TITLE
Using FromCacheAsync doesn't set navigation/relation properties

### ISSUE THREAD

**Issue by joshmouch** [zzzprojects/EntityFramework-Plus#343] opened 2018-04-11 14:21 UTC
I have the following in latest versions of EF Core and Z.EntityFramework.Plus.EFCore:

```
var entityOnes = await dbContext.EntityOnes.Where(blah)
    .Include(a => a.EntityTwos)
    .Include(a => a.EntityThrees)
    .ToListAsync();
```

After this executes, the following works fine, as expected:

```
var test = entityOnes[0].EntityTwos[0].EntityThree.PropertyOne;
```

However, if I change this query to use EntityFrameworkPlus, EntityThree becomes null.  It no longer automatically sets the navigation property:

```
var entityOnes = await dbContext.EntityOnes.Where(blah)
    .Include(a => a.EntityTwos)
    .Include(a => a.EntityThrees)
    .FromCacheAsync(new MemoryCacheEntryOptions() { AbsoluteExpiration = DateTimeOffset.Now.AddHours(1) }, cancellationToken);
```

Now the following throws a null exception because the EntityThree property is null:

```
var test = entityOnes[0].EntityTwos[0].EntityThree.PropertyOne;  // EntityThree property is null.
```

**Comment by JonathanMagnan** [comment] 2018-04-11 16:58
Hello @joshmouch ,

Do you think you could provide us a test project with this issue?

It will make easier/faster for my developer to getting started for investigating it.

_We now always ask for a project since we found out that most issues are missing some essential information or are resolved by the requestor when creating it_

_(Even if the issue seem very easy to reproduce, by getting a test project, it allow us to give a faster support and better experience for the support of all our free libraries)_

Best Regards,

Jonathan

**Comment by joshmouch** [comment] 2018-04-11 16:59
@JonathanMagnan Do you have a template I can use and modify?

**Comment by JonathanMagnan** [comment] 2018-04-11 17:02
Here is the template we normally use when replicating an issue

```csharp
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Request
{
    public static class Request
    {
        public const string connection = "Server=127.0.0.1;Initial Catalog=Z;Integrated Security=True;";

        public static void Execute()
        {  
            // CLEAN
            using (var context = new EntityContext())
            {
                context.EntitySimples.RemoveRange(context.EntitySimples);
                context.SaveChanges();
            }

            // SEED
            using (var context = new EntityContext())
            {
                context.EntitySimples.Add(new EntitySimple() { ColumnInt = 1 });
                context.EntitySimples.Add(new EntitySimple() { ColumnInt = 2 });
                context.EntitySimples.Add(new EntitySimple() { ColumnInt = 3 });
                context.SaveChanges();
            }

            // TEST
            using (var context = new EntityContext())
            {
                var list = context.EntitySimples.ToList(); 
            }
        }

        public class EntityContext : DbContext
        {
            public EntityContext() : base(connection)
            {
            }

            public DbSet<EntitySimple> EntitySimples { get; set; }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                modelBuilder.Types().Configure(x =>
                    x.ToTable(GetType().DeclaringType != null
                        ? GetType().DeclaringType.FullName.Replace(".", "_") + "_" + x.ClrType.Name
                        : ""));

                base.OnModelCreating(modelBuilder);
            }
        }

        public class EntitySimple
        {
            public int ID { get; set; }
            public int ColumnInt { get; set; }
        }
    }
}
```

Thank a lot ;)

**Comment by JonathanMagnan** [comment] 2018-04-30 18:46
Hello @joshmouch ,

This issue will be closed since we haven't heard back from you.

Feel free to reopen it if you can provide the information we asked.

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2018-04-30 18:46 UTC

**Comment by joshmouch** [comment] 2018-04-30 19:12
OK.  I have it on my task list to give you an example, but it probably won't be for quite a while.  I'm just not going to use the Cache for now until I can get back to it.
