### ISSUE TITLE
Dynamic IncludeFilter

### ISSUE THREAD

**Issue by sabandurna** [zzzprojects/EntityFramework-Plus#112] opened 2017-01-30 10:55 UTC
Hi,
I want to use **IncludeFilter** expression in repository in my project. So It must be dynamic. I found a solution that like dynamic linq. 
`context.Branches.Execute<IQueryable<Branch>>("IncludeFilter(d=>d.UserRoles.Where(s=>s.RecordStatus == 1))")` 
But it is not filter child list (UserRoles). 

Can anyone help me please?
Thanks.

**Comment by JonathanMagnan** [comment] 2017-01-31 02:11
Hello @sabandurna ,

Unfortunately, we are not able to reproduce this issue. From our side, it works correctly.

Are you receiving an error? What's the SQL generated?

Here is the example we tried:
```csharp
EvalManager.DefaultContext.RegisterExtensionMethod(typeof(QueryIncludeFilterExtensions));

using (var ctx = new TestContext())
{
    var list1 = ctx.Association_Multi_OneToMany_Lefts.Execute<IQueryable<Association_Multi_OneToMany_Left>>("IncludeFilter(x => x.Right1s.Where(y => y.ColumnInt < 50))").ToList();
}
```

Best Regards,

Jonathan

**Comment by sabandurna** [comment] 2017-01-31 05:49
Hi Jonathan,
I caught generated a Sql Query of the EF query and I found where the problem is. 
It is generated Sql Query for child table: 

`SELECT [Extent2].[Id] AS [Id]`
`		,[Extent3].[Id] AS [Id1]`
`		,[Extent3].[User_Id] AS [User_Id]`
`		,[Extent3].[Role_Id] AS [Role_Id]`
`		,[Extent3].[RecordStatus] AS [RecordStatus]`
`		,[Extent3].[Branch_Id] AS [Branch_Id]`
`		,CASE `
`			WHEN ([Extent3].[RecordStatus] IS NULL)`
`				THEN CAST(NULL AS INT)`
`			ELSE 1`
`			END AS [C1]`
`		,1 AS [C2]`
`	FROM [mng].[Branch] AS [Extent2]`
`	LEFT OUTER JOIN [mng].[UserRole] AS [Extent3] ON ([Extent2].[Id] = [Extent3].[Branch_Id])`
`		AND (1 = [Extent3].[RecordStatus])`
`	WHERE 1 = [Extent2].[RecordStatus]`

It seems that the problem is using **Left Join** instead of **Inner Join**. When I replace the join type with **Inner Join** it works correctly. 

Do you have any idea?

Thanks

**Comment by JonathanMagnan** [comment] 2017-01-31 14:09
Hello @sabandurna ,

IncludeFilter allows making where clause on items that will be included only. So it's normal a LEFT JOIN is performed since it should not filter the "Branch" table.

I believe to achieve your desired result, you will need to perform the where clause twice:

- Once to filter the Branch
- Once to filter included UserRole

Example:
```csharp
context.Branches.Execute<IQueryable<Branch>>(@"
Where(d=>d.UserRoles.Where(s=>s.RecordStatus == 1))
.IncludeFilter(d=>d.UserRoles.Where(s=>s.RecordStatus == 1))")
```

If you don't need the UserRole, you can simple use the Where clause:
```csharp
context.Branches.Execute<IQueryable<Branch>>("Where(d=>d.UserRoles.Where(s=>s.RecordStatus == 1))")
```

Let me know if that helped you with your issue.

Best Regards,

Jonathan

**Comment by sabandurna** [comment] 2017-02-01 07:49
Hi @JonathanMagnan ,
I have tried your sample code you have given me above but no chance. It did not work. 
Then I have run this code that brings 4 UserRoles records:
```
context.Branches.IncludeFilter(s => s.UserRoles.Where(d => d.RecordStatus == 1));
``` 

However The below code brings 6 UserRoles records which means the code between quotation marks did not work:
```
context.Branches.Execute<IQueryable<Branch>>("IncludeFilter(s => s.UserRoles.Where(d => d.RecordStatus == 1))").ToList();
```

Thanks for your support.

Best Regards,
Saban

**Comment by JonathanMagnan** [comment] 2017-02-02 15:57
Hello @sabandurna ,

Can you show the SQL generated for both queries? It should be the same.

The only thing which may impact the number of results is when some relationship is already loaded: [EF Query IncludeFilter - Limitations](https://github.com/zzzprojects/EntityFramework-Plus/wiki/EF-Query-IncludeFilter-%7C-Entity-Framework-Include-Related-Entities-using-Where-Filter#limitations)

Best Regards,

Jonathan

**Comment by sabandurna** [comment] 2017-02-13 07:49
Hi @JonathanMagnan ,
I've compared two generated queries. This is the one that generates expected result .

```
context.Branches.IncludeFilter(s => s.UserRoles.Where(d => d.RecordStatus == 1));

Sql Query: 
SELECT [Extent1].[Id] AS [Id]
FROM [mng].[Branch] AS [Extent1]
LEFT OUTER JOIN (
	SELECT [Extent2].[Id] AS [Id]
		,[Extent3].[Id] AS [Id1]
		,[Extent3].[User_Id] AS [User_Id]
		,[Extent3].[Role_Id] AS [Role_Id]
	FROM [mng].[Branch] AS [Extent2]
	LEFT OUTER JOIN [mng].[UserRole] AS [Extent3] ON ([Extent2].[Id] = [Extent3].[Branch_Id])
		AND (1 = [Extent3].[RecordStatus])
	WHERE 1 = [Extent2].[RecordStatus]
	) AS [Project1] ON 1 = 1
WHERE 1 = [Extent1].[RecordStatus]

```

The another one that generates unexpected result is below.
```
context.Branches.Execute<IQueryable<Branch>>("IncludeFilter(s => s.UserRoles.Where(d => d.RecordStatus == 1))").ToList();

Sql Query:
SELECT [Extent1].[Id] AS [Id]
FROM [mng].[Branch] AS [Extent1]
LEFT OUTER JOIN (
	SELECT [Extent2].[Id] AS [Id]
		,[Extent3].[Id] AS [Id1]
		,[Extent3].[User_Id] AS [User_Id]
		,[Extent3].[Role_Id] AS [Role_Id]
	FROM [mng].[Branch] AS [Extent2]
	LEFT OUTER JOIN [mng].[UserRole] AS [Extent3] ON ([Extent2].[Id] = [Extent3].[Branch_Id])
		AND (1 = [Extent3].[RecordStatus])
	) AS [Project1] ON 1 = 1
WHERE 1 = [Extent1].[RecordStatus]

```

Thanks
Saban

**Comment by JonathanMagnan** [comment] 2017-02-13 15:00
Hello @sabandurna,

The only difference between both SQL is the following line:

```sql
WHERE 1 = [Extent2].[RecordStatus]
-- [Extent2] = Branch
```

The Filter you apply is here in both SQL

```csharp
`UserRoles.Where(d => d.RecordStatus == 1)` 
```

```sql
`AND (1 = [Extent3].[RecordStatus]`
-- [Extent3] = UserRole
```


What I don't understand is how your first SQL generate this additional filter. There is nothing in your LINQ that say to filter also the Branch table.

Are you sure you use the same LINQ? Perhaps in the first example there is an additional filter which cause the difference?

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-05-17 00:26
Closing comment: No answer, feel free to re-open with more information

**Closed by JonathanMagnan** 2017-05-17 00:26 UTC
