### ISSUE TITLE
IncludeOptimized Where + Select = OutOfMemoryException

### ISSUE THREAD

**Issue by FilipFilipov** [zzzprojects/EntityFramework-Plus#125] opened 2017-02-15 13:30 UTC
I'm trying to retrieve some objects with several levels of related entities while skipping some that are soft-deleted. I tried using IncludeOptimized with `QueryIncludeOptimizedManager.AllowIncludeSubPath = true`

The query goes something like this:
```
var sections = db.CustomerProfileSections
    .IncludeOptimized(cps => cps.CustomerProfileSectionFields
         .Where(cpsf => !cpsf.IsDeleted)
         .Select(cpsf => cpsf.DataAttribute.DataEntity.DataSource))
     .ToArray();
```
And throws the exception:
```
System.OutOfMemoryException : Array dimensions exceeded supported range.
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
   at System.Collections.Generic.List`1.Add(T item)
   at Z.EntityFramework.Plus.QueryIncludeOptimizedExpressionToReduceVisitor.VisitLambda[T](Expression`1 node)
   at Z.EntityFramework.Plus.QueryIncludeOptimizedIncludeSubPath.IncludeSubPath[T](IQueryable`1 query, Expression expression)
   at Z.EntityFramework.Plus.QueryIncludeOptimizedExtensions.IncludeOptimizedSingle[T,TChild](IQueryable`1 query, Expression`1 queryIncludeFilter)
```

I can move the where clause to a global query filter, and it will work, but they seem to have their own issues with multi-level includes, so it's not a full proof solution.

**Comment by JonathanMagnan** [comment] 2017-02-16 12:17
Hello @FilipFilipov ,

Thank you for reporting this issue,

We will try to fix this issue this weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-02-19 23:23
Hello @FilipFilipov ,

The v1.4.31 is now available.

We fixed this issue which was caused by an infinite loop.

Let me know if it's now working.

Best Regards,

Jonathan

**Comment by FilipFilipov** [comment] 2017-02-20 07:15
Yup, that fixed it, thanks!

**Comment by JonathanMagnan** [comment] 2017-02-20 15:34
Closing Comment: Fix confirmed

**Closed by JonathanMagnan** 2017-02-20 15:34 UTC
