### ISSUE TITLE
Pomelo.MySql and BatchUpdate issue

### ISSUE THREAD

**Issue by rooonikz** [zzzprojects/EntityFramework-Plus#341] opened 2018-04-06 18:31 UTC
Hi! I have such query
`                await _dataContext
                    .Users
                    .Where(x => x.Id == request.SellerId)
                    .UpdateAsync(user => new User {Property= user.Property+ someValue}, cancellationToken);`

During SQL generation I have an SQL, that listed below, but it is generated incorrect as MySQL connector throws an exception `MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown column 'x.amount_due' in 'field list'`. It seems that BatchUpdate somehow catches the closure name `x` and insert it in result query. Could you please provide me what I am doing wrong?

```
UPDATE `user` AS A
INNER JOIN 
(SELECT `x`.`Id`, `x`.`Property`, `x`.`CompanyId`, `x`.`ConcurrencyStamp`, `x`.`DrivingLicense`, `x`.`Email`, `x`.`EmailConfirmed`, `x`.`FirstName`, `x`.`IsActive`, `x`.`LastName`, `x`.`NormalizedEmail`, `x`.`NormalizedUserName`, `x`.`PasswordHash`, `x`.`PhoneNumber`, `x`.`RegisteredAt`, `x`.`SecurityStamp`, `x`.`UserName`
FROM `fifty_fifty`.`user` AS `x`
WHERE `x`.`Id` = 1) 
AS B ON A.`Id` = B.`Id`
SET A.`Property` = `x`.`Property` + 5
```

EF Core 2.0, ASP.NET Core 2.0.1

**Comment by JonathanMagnan** [comment] 2018-04-08 19:45
Hello @rooonikz ,

Do you think you could provide us a test project with this issue?

It will make easier/faster for my developer to getting started for investigating it.

_We now always ask for a project since we found out that most issues are missing some essential information or are resolved by the requestor when creating it_

_(Even if the issue seem very easy to reproduce, by getting a test project, it allow us to give a faster support and better experience for the support of all our free libraries)_

Best Regards,

Jonathan

**Comment by rooonikz** [comment] 2018-04-09 08:12
@JonathanMagnan Thanks for your response! Unfortunately, I don't have enough time this week to prepare for you test project, may be I can do it on the weekend. But I am fully open for you developer for providing additional information!

Thanks!

**Comment by JonathanMagnan** [comment] 2018-04-30 18:45
Hello @rooonikz ,

This issue will be closed since we haven't heard back from you.

Feel free to reopen it if you can provide the information we asked.

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2018-04-30 18:45 UTC

**Comment by Kir-Antipov** [comment] 2019-09-07 01:06
Faced the same error. As I understood, no one has solved this issue?
