### ISSUE TITLE
FutureQueries are incompatible with Effort.EF6

### ISSUE THREAD

**Issue by gandhibobandhi** [zzzprojects/EntityFramework-Plus#260] opened 2017-10-23 16:55 UTC
Hey,

I've been using Effort.EF6 to write some unit tests for some code that uses entity framework and EF.Plus. The issue I've bumped into is regarding FutureQueries- It seems that any query that uses .Future() throws a NotSupportedException when the underlying connection is to an Effort database.

I notice that there was a previous pull request with a fix for batch updating and deleting- could this be a symptom of the same problem?

Thanks,
Adam

**Comment by JonathanMagnan** [comment] 2017-10-23 23:21
Hello @gandhibobandhi ,

Yes, this is exactly the same problem.

We will look at it soon to see what we can do. I cannot guarantee we will be able to look at it this week since the workload for this library is currently very high but we will try to look as soon as possible.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-11-04 18:44
Hello @gandhibobandhi ,

Sorry for the delay,

The fix has been completed and will be part of the next release that will be done on Monday or before.

I will let you know as soon as this new version is available.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-11-07 02:29
Hello @sparkybg ,

The version 1.7.6 has been released:
https://github.com/zzzprojects/EntityFramework-Plus/releases/tag/v1.7.6

Let me know if Query Future now support correctly `Effort`

Best Regards,

Jonathan

**Comment by gandhibobandhi** [comment] 2017-11-07 11:45
Thanks!  I'll give it a test today and let you know how it goes. :)

**Comment by gandhibobandhi** [comment] 2017-11-07 12:14
Works a charm! Thanks again!

**Comment by JonathanMagnan** [comment] 2017-11-07 13:43
Great ;)

**Comment by 100s** [comment] 2018-10-18 13:03
Hi!

Looks like it still does not work for asyncs:

```
var dbContext = new IncidentDbContext(Effort.DbConnectionFactory.CreateTransient(), "ntext");
var results1 = dbContext.Incidents.Future();
var results2 = dbContext.Incidents.Future();
// Specified method is not supported.
var dd = await results1.ToListAsync();
```

When using just ToList() it works fine. It works on real database.

Effort.EF6 1.3.10
Z.EntityFramework.Plus.EF6

**Comment by JonathanMagnan** [comment] 2018-10-18 19:34
Thank you for reporting, we successfully reproduced it.

One of my developers will look soon at it.

```csharp
using System.Data.Common;
using System.Data.Entity;
using System.Linq;
using System.Windows.Forms;
using Effort;

namespace Z.EntityFramework.Plus.Lab.EF6
{
    public partial class Form_Request_Effort_QueryFuture : Form
    {
        public Form_Request_Effort_QueryFuture()
        {
            InitializeComponent();

            var effortConnection = DbConnectionFactory.CreateTransient();

            // SEED
            using (var context = new EntityContext(effortConnection))
            {
                context.EntitySimple.Add(new EntitySimple() {ColumnInt = 1});
                context.SaveChanges();
            }


            // TEST
            using (var context = new EntityContext(effortConnection))
            {
                var a = context.EntitySimple.Future();
                var b = context.EntitySimple.Where(x => x.ColumnInt > 0).Future();
                var listTask = a.ToListAsync().Result;
            }
        }


        public class EntityContext : DbContext
        {
            public EntityContext(DbConnection connection) : base(connection, false)
            {
            }

            public DbSet<EntitySimple> EntitySimple { get; set; }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                modelBuilder.Types().Configure(x =>
                    x.ToTable(GetType().DeclaringType != null
                        ? GetType().DeclaringType.FullName.Replace(".", "_") + "_" + x.ClrType.Name
                        : ""));

                base.OnModelCreating(modelBuilder);
            }
        }

        public class EntitySimple
        {
            public int ID { get; set; }
            public int ColumnInt { get; set; }
        }
    }
}
```

**Comment by JonathanMagnan** [comment] 2018-10-23 23:33
Hello @100s ,

The v1.8.11 has been released.

Could you try it and let me know if the issue with `Effort` has been fixed?

Best Regards,

Jonathan

**Comment by 100s** [comment] 2018-10-25 07:06
Hi

It still does not work for me. Now I have exception: Object reference not set to an instance of an object.

Stack trace:
```
   at Z.EntityFramework.Plus.QueryFutureBatch.CreateCommandCombined() in C:\Users\Jonathan\Desktop\Z\TFS\EFPlus\Z.EntityFramework.Plus\shared\Z.EF.Plus.QueryFuture.Shared\QueryFutureBatch.cs:line 375
   at Z.EntityFramework.Plus.QueryFutureBatch.<ExecuteQueriesAsync>d__10.MoveNext() in C:\Users\Jonathan\Desktop\Z\TFS\EFPlus\Z.EntityFramework.Plus\shared\Z.EF.Plus.QueryFuture.Shared\QueryFutureBatch.cs:line 245
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Z.EntityFramework.Plus.QueryFutureEnumerable`1.<ToListAsync>d__4.MoveNext() in C:\Users\Jonathan\Desktop\Z\TFS\EFPlus\Z.EntityFramework.Plus\shared\Z.EF.Plus.QueryFuture.Shared\QueryFutureEnumerable.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
...
```

**Comment by JonathanMagnan** [comment] 2018-11-11 03:18
Hello @100s,

This issue will be closed since we haven't heard back from you.

Feel free to reopen if you can provide further information.

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2018-11-11 03:18 UTC
