### ISSUE TITLE
null reference exception on delete

### ISSUE THREAD

**Issue by AlexeyTipunin** [zzzprojects/EntityFramework-Plus#7] opened 2016-05-06 13:20 UTC
Hello.

When I try to execute this code, I get null reference exception. Whats wrong?
`        public void RemoveRangeAsNoTracking(IEnumerable<TagTrend> trends)
        {
            var ids = trends.Select(s => s.TagTrendId).ToArray();
            Context.Set<TagTrend>().Where(w => ids.Contains(w.TagTrendId)).Delete();
        }`
Stack trace:
`   в Z.EntityFramework.Plus.BatchDelete.Execute[T](IQueryable`1 query)
   в Z.EntityFramework.Plus.BatchDeleteExtensions.Delete[T](IQueryable`1 query, Action`1 batchDeleteBuilder)
   в Z.EntityFramework.Plus.BatchDeleteExtensions.Delete[T](IQueryable`1 query)
   в TankBatteryPostgreSqlEntitysLibrary.DAL.TagTrendRepository.RemoveRangeAsNoTracking(IEnumerable`1 trends) в D:\ПТК РП\TankBattery\TankBatteryPostgreSqlEntitysLibrary\DAL\TagTrendRepository.cs:строка 52
   в HMI.Infrastructure.DataCleaner.ClearTrends() в D:\ПТК РП\TankBattery\HMI\Infrastructure\DataCleaner.cs:строка 84`
Entity Framework Core.

**Comment by zzzprojects** [comment] 2016-05-06 13:26
Hello Alexey,

Unfortunately, your code is right but the PostgreSQL is not supported for this features yet. Only SQL Server and SQL Azure are supported for now.

Best Regards,

Jonathan

**Comment by AlexeyTipunin** [comment] 2016-05-06 13:34
Thanks for the quick response.
Do you plan to implement for PostgreSQL.

**Comment by zzzprojects** [comment] 2016-05-06 13:53
Yes, we plan to implement PostgreSQL.

We are currently completing PostgreSQL tests for Entity Framework Extensions. I will try to get a look for BatchDelete for this provider at the same time next week.

**Comment by zzzprojects** [comment] 2016-05-11 16:46
Hello Alexey,

The v.1.0.7 for EF5 && EF6 should now support PostgreSQL for the BatchDelete features.

Let me know if the issue is fixed for you

**Comment by zzzprojects** [comment] 2016-08-03 14:11
Closing: Fixed in v1.0.7

**Closed by zzzprojects** 2016-08-03 14:11 UTC
